COUNTRY_APP = 'libya'

OPTIONAL_APPS = []

TWITTER_USERNAME = ''
TWITTER_WIDGET_ID = ''

BLOG_RSS_FEED = ''

MAP_BOUNDING_BOX_NORTH = 33.37
MAP_BOUNDING_BOX_EAST = 25.28
MAP_BOUNDING_BOX_SOUTH = 19.43
MAP_BOUNDING_BOX_WEST = 9.22

MAPIT_COUNTRY = 'LY'
