COUNTRY_APP = 'nigeria'

OPTIONAL_APPS = []

TWITTER_USERNAME = 'NGShineyoureye'
TWITTER_WIDGET_ID = '354909651910918144'

BLOG_RSS_FEED = 'http://eienigeria.org/rss.xml'

MAP_BOUNDING_BOX_NORTH = 14.1
MAP_BOUNDING_BOX_EAST = 14.7
MAP_BOUNDING_BOX_SOUTH = 4
MAP_BOUNDING_BOX_WEST = 2.5

MAPIT_COUNTRY = 'NG'
