conversions = { 
    "Abayateye, Alfred W. G.":("Abayateye","Alfred","W. G.","m"), 
    "Abdul-Karim, Iddrisu (Alhaji)":("Abdul-Karim","Iddrisu","","m"), 
    "Abdul-Rahman, Masoud Baba":("Abdul-Rahman","Masoud","Baba","m"), 
    "Abdul-Razaq, A. Umar":("Abdul-Razaq","Umar","A.","m"), 
    "Abongo, Albert":("Abongo","Albert","","m"), 
    "Abu-Bonsra, Nana":("Abu-Bonsra","Nana","","m"), 
    "Abubakari, Ibrahim Dey (Alhaji)":("Abubakari","Ibrahim","Dey","m"), 
    "Abukari, Sumani (Alhaji)":("Abukari","Sumani","","m"), 
    "Acheampong, Kwame Seth":("Acheampong","Kwame","Seth","m"), 
    "Ackah, Stephen M. E. K.":("Ackah","Stephen","M. E. K.","m"), 
    "Adda, Joseph Kofi":("Adda","Joseph","Kofi","m"), 
    "Addae, Christopher":("Addae","Christopher","","m"), 
    "Addai, Simons":("Addai","Simons","","m"), 
    "Addai-Nimoh, Francis":("Addai-Nimoh","Francis","","m"), 
    "Addo, Grace (Ms)":("Addo","Grace","","f"), 
    "Addo, Irene Naa Torshie (Mrs)":("Addo","Irene","Naa Torshie","f"), 
    "Adiyia, Akuoko Richard":("Adiyia","Akuoko","Richard","m"), 
    "Adjaho, Edward K. D.":("Adjaho","Edward","K. D.","m"), 
    "Adjei-Baah, Seth":("Adjei-Baah","Seth","","m"), 
    "Adjei-Yeboah, Andrews":("Adjei-Yeboah","Andrews","","m"), 
    "Adu-Asare, Kojo":("Adu-Asare","Kojo","","m"), 
    "Afeku, Catherine Ablema":("Afeku","Catherine","Ablema","f"), 
    "Afful, Yaw Maama":("Afful","Yaw","Maama","m"), 
    "Afotey-Agbo, Joseph Nii Laryea":("Afotey-Agbo","Joseph","Nii Laryea","m"), 
    "Agbenyefia-Lassey, Richard":("Agbenyefia-Lassey","Richard","","m"), 
    "Agbesi, Alfred Kwame":("Agbesi","Alfred","Kwame","m"), 
    "Agyabeng, John":("Agyabeng","John","","m"), 
    "Agyapong, Ken Ohene":("Agyapong","Ken","Ohene","m"), 
    "Agyeman, Elizabeth":("Agyeman","Elizabeth","","f"), 
    "Agyemang-Manu, Kwaku":("Agyemang-Manu","Kwaku","","m"), 
    "Agyen, Frank Boakye":("Agyen","Frank","Boakye","m"), 
    "Agyenim-Boateng, Kwaku":("Agyenim-Boateng","Kwaku","","m"), 
    "Ahaligah, Raphael Kofi":("Ahaligah","Raphael","Kofi","m"), 
    "Ahi, Sampson":("Ahi","Sampson","","m"), 
    "Ahmed, Mustapha (Maj [rtd]) (Dr) (Alh)":("Ahmed","Mustapha","","m"), 
    "Aidoo, Evans Paul":("Aidoo","Evans","Paul","m"), 
    "Aidoo, Joseph Boahen":("Aidoo","Joseph","Boahen","m"), 
    "Akolbire, Opam-Brown Emmanuel":("Akolbire","Opam-Brown","Emmanuel","m"), 
    "Akologu, John Tia":("Akologu","John","Tia","m"), 
    "Akomea, Nana":("Akomea","Nana","","m"), 
    "Akoto, Owusu Afriyie (Dr)":("Akoto","Owusu","Afriyie","m"), 
    "Akunye, Simon Atingban":("Akunye","Simon","Atingban","m"), 
    "Akyea, Samuel Atta":("Akyea","Samuel","Atta","m"), 
    "Alhasan Dubie, Halutie Rafatu (Hajia)":("Alhasan Dubie","Halutie","Rafatu","f"), 
    "Alhassan, Ahmed Yakubu (Dr)":("Alhassan","Ahmed","Yakubu","m"), 
    "Alidu, Iddrisu Zakari":("Alidu","Iddrisu","Zakari","m"), 
    "Alowe, Leo Kabah":("Alowe","Leo","Kabah","m"), 
    "Amadu, Seidu (Alhaji)":("Amadu","Seidu","","m"), 
    "Amankwanor, Joseph Sam":("Amankwanor","Joseph","Sam","m"), 
    "Amenowode, Joseph Z.":("Amenowode","Joseph","Z.","m"), 
    "Ameyaw-Akumfi, Christopher (Prof)":("Ameyaw-Akumfi","Christopher","","m"), 
    "Ameyaw-Cheremeh, Kwasi":("Ameyaw-Cheremeh","Kwasi","","m"), 
    "Amoah, Anthony Evans":("Amoah","Anthony","Evans","m"), 
    "Amoah, Osei Bonsu":("Amoah","Osei","Bonsu","m"), 
    "Amoah-Tetteh, Elizabeth (Mrs)":("Amoah-Tetteh","Elizabeth","","f"), 
    "Amoako-Attah, Kwasi":("Amoako-Attah","Kwasi","","m"), 
    "Amoakoh, Kwadwo Samuel (Prof)":("Amoakoh","Kwadwo","Samuel","m"), 
    "Amoakoh, Nana":("Amoakoh","Nana","","m"), 
    "Anane, Richard W. (Dr)":("Anane","Richard","W.","m"), 
    "Annan, Joseph (Dr)":("Annan","Joseph","","m"), 
    "Anyimadu-Antwi, Kwame":("Anyimadu-Antwi","Kwame","","m"), 
    "Appiah, Justice Joe":("Appiah","Justice","Joe","m"), 
    "Appiah-Kubi, Kojo (Dr)":("Appiah-Kubi","Kojo","","m"), 
    "Appiah-Ofori, P.C.":("Appiah-Ofori","P.C.","","m"), 
    "Appiah-Pinkrah,  Kwabena":("Appiah-Pinkrah","Kwabena","","m"), 
    "Armah, Ernest Attuquaye":("Armah","Ernest","Attuquaye","m"), 
    "Arthur, Francis Kojo":("Arthur","Francis","Kojo","m"), 
    "Arthur, George Kofi":("Arthur","George","Kofi","m"), 
    "Asaga, Moses":("Asaga","Moses","","m"), 
    "Asare, Kofi (Dr.)":("Asare","Kofi","","m"), 
    "Asare-Akoto, Joses (Rev) (Dr)":("Asare-Akoto","Joses","","m"), 
    "Ashietey, Nii Armah":("Ashietey","Nii","Armah","m"), 
    "Asiamah, Amankwa Kwabena":("Asiamah","Amankwa","Kwabena","m"), 
    "Asiamah, Isaac Kwame":("Asiamah","Isaac","Kwame","m"), 
    "Asimah, Simon Edem":("Asimah","Simon","Edem","m"), 
    "Assumeng, David Tetteh":("Assumeng","David","Tetteh","m"), 
    "Asum-Ahensah, Alex":("Asum-Ahensah","Alex","","m"), 
    "Avedzi,  James Klutse":("Avedzi","James","Klutse","m"), 
    "Avoka, Apul Cletus":("Avoka","Apul","Cletus","m"), 
    "Awontiirim, Ataboadey Timothy":("Awontiirim","Ataboadey","Timothy","m"), 
    "Awuah, Ignatius Baffour":("Awuah","Ignatius","Baffour","m"), 
    "Ayeh, Benjamin Kofi":("Ayeh","Benjamin","Kofi","m"), 
    "Ayeh-Paye, Samuel":("Ayeh-Paye","Samuel","","m"), 
    "Azong, Alhassan":("Azong","Alhassan","","m"), 
    "Azumah, Dominic Azimbe":("Azumah","Dominic","Azimbe","m"), 
    "Azumah-Mensah, Juliana (Mrs)":("Azumah-Mensah","Juliana","","f"), 
    "Baah, Yaw":("Baah","Yaw","","m"), 
    "Baffour, Fritz Frederic":("Baffour","Fritz","Frederic","m"), 
    "Bagbin, Alban S. K.":("Bagbin","Alban","S. K.","m"), 
    "Baidoe-Ansah, Joe":("Baidoe-Ansah","Joe","","m"), 
    "Baloroo, Duoghr John":("Baloroo","Duoghr","John","m"), 
    "Banda, Ben Abdallah":("Banda","Ben","Abdallah","m"), 
    "Bandua, Emmanuel Kwasi":("Bandua","Emmanuel","Kwasi","m"), 
    "Barton-Odro, Ebo":("Barton-Odro","Ebo","","m"), 
    "Bayirga, Haruna H.":("Bayirga","Haruna","H.","m"), 
    "Bayon, Godfrey Tangu":("Bayon","Godfrey","Tangu","m"), 
    "Bedzrah, Emmanuel Kwasi":("Bedzrah","Emmanuel","Kwasi","m"), 
    "Bennam, John Jabaah":("Bennam","John","Jabaah","m"), 
    "Blankson, George Kuntu":("Blankson","George","Kuntu","m"), 
    "Boafo, William Ofori":("Boafo","William","Ofori","m"), 
    "Boakye, George":("Boakye","George","","m"), 
    "Boampong, Michael Coffie":("Boampong","Michael","Coffie","m"), 
    "Boateng, Bernice Beatrice (Ms)":("Boateng","Bernice","Beatrice","m"), 
    "Boforo, Mary Salifu (Hajia)":("Boforo","Mary","Salifu","m"), 
    "Bosompem, Joseph Ampomah":("Bosompem","Joseph","Ampomah","m"), 
    "Botchway, Shirley A. (Ms)":("Botchway","Shirley","A.","f"), 
    "Botwe, Daniel":("Botwe","Daniel","","m"), 
    "Buah, Emmanuel Armah-Kofi":("Buah","Emmanuel","Armah-Kofi","m"), 
    "Bukari, Joseph Nikpe":("Bukari","Joseph","Nikpe","m"), 
    "Chaie, Theophilus Tetteh":("Chaie","Theophilus","Tetteh","m"), 
    "Chireh, Joseph Yieleh":("Chireh","Joseph","Yieleh","m"), 
    "Cobbina, Herod":("Cobbina","Herod","","m"), 
    "Dadzie, Anthony Christian":("Dadzie","Anthony","Christian","m"), 
    "Dakura, Francis Bawaana (Dr.)":("Dakura","Francis","Bawaana","m"), 
    "Dansua, Akua Sena (Ms)":("Dansua","Akua","Sena","f"), 
    "Dapaah, Cecilia Abena (Ms)":("Dapaah","Cecilia","Abena","m"), 
    "Daramani-Sakande, Adamu":("Daramani-Sakande","Adamu","","m"), 
    "Darko-Mensah, Kwabena Okyere":("Darko-Mensah","Kwabena","Okyere","m"), 
    "Dauda, Collins (Alhaji)":("Dauda","Collins","","m"), 
    "Debrah, Ernest Akobuor":("Debrah","Ernest","Akobuor","m"), 
    "Dery, P. Ambrose":("Dery","P. Ambrose","","m"), 
    "Didieye, Aboagye Emmanuel":("Didieye","Aboagye","Emmanuel","m"), 
    "Donkor, Benjamin B. (Rev)":("Donkor","Benjamin","B.","m"), 
    "Dua, Nii Nortey R.":("Dua","Nii","Nortey R.","m"), 
    "Duut, Emmanuel Kwame":("Duut","Emmanuel","Kwame","m"), 
    "Eduamoah, Ekow Panyin Okyere":("Eduamoah","Ekow","Panyin Okyere","m"), 
    "Effah-Baafi, Yaw":("Effah-Baafi","Yaw","","m"), 
    "Ennin, Edward  M.":("Ennin","Edward","M.","m"), 
    "Essilfie, Gabriel Kodwo":("Essilfie","Gabriel","Kodwo","m"), 
    "Fobih, Dominic K. (Prof)":("Fobih","Dominic","K.","m"), 
    "Forson, Cassiel Ato":("Forson","Cassiel","Ato","m"), 
    "Frimpong, Kofi":("Frimpong","Kofi","","m"), 
    "Fuseini, Inusah Abdulai B.":("Fuseini","Inusah","Abdulai B.","m"), 
    "Gbediame, Gershon K. B.":("Gbediame","Gershon","K. B.","m"), 
    "Ghartey, Joe":("Ghartey","Joe","","m"), 
    "Gidisu, Joe Kwashie":("Gidisu","Joe","Kwashie","m"), 
    "Gidisu, Wisdom":("Gidisu","Wisdom","","m"), 
    "Gyamfi, Emmanuel Akwasi":("Gyamfi","Emmanuel","Akwasi","m"), 
    "Gyan-Baffour, George Yaw (Prof)":("Gyan-Baffour","George","Yaw","m"), 
    "Gyetuah, John":("Gyetuah","John","","m"), 
    "Hammah, Mike Allen":("Hammah","Mike","Allen","m"), 
    "Hammond, Kobina Tahir":("Hammond","Kobina","Tahir","m"), 
    "Hayibor, Prince Jacob":("Hayibor","Prince","Jacob","m"), 
    "Hodogbey, Charles S.":("Hodogbey","Charles","S.","m"), 
    "Humado, Clement Kofi":("Humado","Clement","Kofi","m"), 
    "Ibrahim, Ahmed":("Ibrahim","Ahmed","","m"), 
    "Ibrahim, Tanko Abdul-Rauf":("Ibrahim","Tanko","Abdul-Rauf","m"), 
    "Iddrisu, Dawuda":("Iddrisu","Dawuda","","m"), 
    "Iddrisu, Haruna":("Iddrisu","Haruna","","m"), 
    "Iddrisu, Sulemana Ibun (Baba)":("Iddrisu","Sulemana","Ibun","m"), 
    "Imoro, Yakubu Kakpagu":("Imoro","Yakubu","Kakpagu","m"), 
    "Jabanyite, Samuel Abdulai":("Jabanyite","Samuel","Abdulai","m"), 
    "Johnfiah, Samuel":("Johnfiah","Samuel","","m"), 
    "Jumah, Maxwell Kofi":("Jumah","Maxwell","Kofi","m"), 
    "Kamel, Henry Ford":("Kamel","Henry","Ford","m"), 
    "Kan-Dapaah Albert":("Kan-Dapaah","Albert","","m"), 
    "Klenam, Gifty":("Klenam","Gifty","","f"), 
    "Koffie, Francis Adu-Blay":("Koffie","Francis","Adu-Blay","m"), 
    "Kunsu, Stephen":("Kunsu","Stephen","","m"), 
    "Kusi, Gifty Eugenia (Mrs)":("Kusi","Gifty","Eugenia","f"), 
    "Kwao, Stephen Amoanor":("Kwao","Stephen","Amoanor","m"), 
    "Kyei-Mensah-Bonsu, Osei":("Kyei-Mensah-Bonsu","Osei","","m"), 
    "Larbie, David Nana":("Larbie","David Nana","","m"), 
    "Likpalimor, Kwajo Tawiah":("Likpalimor","Kwajo","Tawiah","m"), 
    "Manu, S. K. Balado":("Manu","S. K.","Balado","m"), 
    "Mensah, Enoch Teye":("Mensah","Enoch","Teye","m"), 
    "Mohammed, Issifu Pangabu (Alhaji)":("Mohammed","Issifu","Pangabu","m"), 
    "Muntaka, Mubarak Mohammed (Alhaji)":("Muntaka","Mubarak","Mohammed","m"), 
    "Namoale, Nii Amasah":("Namoale","Nii","Amasah","m"), 
    "Narh, Samuel Evans Ashong":("Narh","Samuel","Evans Ashong","m"), 
    "Nasah, Thomas Kwesi":("Nasah","Thomas","Kwesi","m"), 
    "Nayan, Joseph Kwaku":("Nayan","Joseph","Kwaku","m"), 
    "Nfojoh, G. K. (Capt) (rtd)":("Nfojoh","G. K.","","m"), 
    "Nitiwul, Dominic B. A.":("Nitiwul","Dominic","B. A.","m"), 
    "Nkrumah, Samia Yaba Christiana":("Nkrumah","Samia","Yaba Christiana","f"), 
    "Ntim, Augustine Collins":("Ntim","Augustine","Collins","m"), 
    "Ntow, Mathias Kwame":("Ntow","Mathias","Kwame","m"), 
    "Ntow-Ababio, Yaw":("Ntow-Ababio","Yaw","","m"), 
    "Nyaunu, Michael Teye":("Nyaunu","Michael","Teye","m"), 
    "Obeng Dappah, Esther (Ms)":("Obeng Dappah","Esther","","f"), 
    "Obodai, Samuel K.":("Obodai","Samuel","K.","m"), 
    "Oduro, Derek Yaw (Maj. [rtd])":("Oduro","Derek","Yaw","m"), 
    "Ofori, Joseph Kwadwo":("Ofori","Joseph","Kwadwo","m"), 
    "Ofori-Kuragu, E. Nana Yaw":("Ofori-Kuragu","E.","Nana Yaw","m"), 
    "Ofosu, Asamoah":("Ofosu","Asamoah","","m"), 
    "Ohene-Konadu, Gifty (Mrs)":("Ohene-Konadu","Gifty","","f"), 
    "Okoh, Paul":("Okoh","Paul","","m"), 
    "Opare-Ansah, Frederick":("Opare-Ansah","Frederick","","m"), 
    "Oppon-Kusi, David":("Oppon-Kusi","David","","m"), 
    "Oquaye, Aaron  Michael (Prof.)":("Oquaye","Aaron","Michael","m"), 
    "Osei, Anthony Akoto  (Dr)":("Osei","Anthony","Akoto","m"), 
    "Osei, Isaac":("Osei","Isaac","","m"), 
    "Osei-Mensah, Simon":("Osei-Mensah","Simon","","m"), 
    "Osei-Opare, Akosua Frema (Mrs)":("Osei-Opare","Akosua","Frema","f"), 
    "Osei-Owusu, Joseph":("Osei-Owusu","Joseph","","m"), 
    "Osei-Prempeh, Kwame":("Osei-Prempeh","Kwame","","m"), 
    "Osei-Sarfo, Francis Yaw":("Osei-Sarfo","Francis","Yaw","m"), 
    "Owusu-Aduomi, Kwabena":("Owusu-Aduomi","Kwabena","","m"), 
    "Owusu-Agyemang, Hackman":("Owusu-Agyemang","Hackman","","m"), 
    "Owusu-Ankomah, Papa":("Owusu-Ankomah","Papa","","m"), 
    "Owusu-Ansah, Emmanuel Asamoah (DECEASED - 22/06/12)":("Owusu-Ansah","Emmanuel","Asamoah","m"), 
    "Owusu-Bio, Benito":("Owusu-Bio","Benito","","m"), 
    "Owusu-Boateng, Yaw":("Owusu-Boateng","Yaw","","m"), 
    "Owusu-Mainu, Emmanuel":("Owusu-Mainu","Emmanuel","","m"), 
    "Pelpuo, Abdul-Rashid":("Pelpuo","Abdul-Rashid","","m"), 
    "Pepera, Peter Wiafe":("Pepera","Peter","Wiafe","m"), 
    "Prempeh, Matthew Opoku (Dr)":("Prempeh","Matthew","Opoku","m"), 
    "Puozaa, Mathias A.":("Puozaa","Mathias","A.","m"), 
    "Quansah, Aquinas":("Quansah","Aquinas","","m"), 
    "Quaye, I. C. (Sheikh)":("Quaye","I. C.","","m"), 
    "Quaye-Kumah, Nii Oakley (Dr)":("Quaye-Kumah","Nii","Oakley","m"), 
    "Saaka, Joseph Akati":("Saaka","Joseph","Akati","m"), 
    "Saani, Iddi (Alhaji) (DECEASED - 05/06/12)":("Saani","Iddi","","m"), 
    "Sackey, Elizabeth K. T. (Mrs)":("Sackey","Elizabeth","K. T.","f"), 
    "Sarfo-Mensah, Robert":("Sarfo-Mensah","Robert","","m"), 
    "Soditey, Donald Dari":("Soditey","Donald","Dari","m"), 
    "Sorogho, Amadu B. (Alhaji)":("Sorogho","Amadu","B.","m"), 
    "Tackie-Komme, Jonathan":("Tackie-Komme","Jonathan","","m"), 
    "Tawiah, Raymond A.":("Tawiah","Raymond","A.","m"), 
    "Tettey-Enyo, Alexander Narh":("Tettey-Enyo","Alexander","Narh","m"), 
    "Tia, Alfred Sugri (Dr)":("Tia","Alfred","Sugri","m"), 
    "Twumasi, Kwame Amporfo":("Twumasi","Kwame","Amporfo","m"), 
    "Twumasi-Appiah, Felix":("Twumasi-Appiah","Felix","","m"), 
    "Woyome, Kobla Mensah":("Woyome","Kobla","Mensah","m"), 
    "Wusah, Sammy B.":("Wusah","Sammy","B.","m"), 
    "Yakah, Ernest Kofi":("Yakah","Ernest","Kofi","m"), 
    "Yakubu, Stephen":("Yakubu","Stephen","","m"), 
    "Yeboah, David Hennric":("Yeboah","David","Hennric","m"), 
    "Yemoh, Daoud Anum":("Yemoh","Daoud","Anum","m"), 
    "Zigah, Albert Kwasi":("Zigah","Albert","Kwasi","m"), 
}
