conversions = {
    "Abdikadir, Hussein": ("Abdikadir", "Hussein", ""),
    "Abu, Mohamed": ("Abu", "Mohamed", ""),
    "Abuchiaba, Ali Mohammed": ("Abuchiaba", "Ali", "Mohammed"),
    "Akula, Bulimo Evans": ("Akula", "Bulimo", "Evans"),
    "Aluoch, Olago John": ("Aluoch", "Olago", "John"),
    "Anyanga, Omondi Edick Peter": ("Anyanga", "Omondi", "Edick Peter"),
    "Anyango, Pollyins Ochieng": ("Anyango", "Pollyins", "Ochieng"),
    "Bahari, Abdul Ali": ("Bahari", "Abdul", "Ali"),
    "Baiya, Peter Njoroge": ("Baiya", "Peter", "Njoroge"),
    "Balala, Najib Mohamed": ("Balala", "Najib", "Mohamed"),
    "Bayah, Francis S.K.": ("Bayah", "Francis", "S.K."),
    "Bett, Franklin Kipn'getich": ("Bett", "Franklin", "Kipn'getich"),
    "Chanzu, Kifuma Yusuf": ("Chanzu", "Kifuma", "Yusuf"),
    "Chepchumba Peris": ("Peris", "Chepchumba", ""),
    "Chepkitony, Lucas Kipkosgey": ("Chepkitony", "Lucas", "Kipkosgey"),
    "Cheuriyot, Zakayo Kipkemoi": ("Cheuriyot", "Zakayo", "Kipkemoi"),
    "Dwale, Aden Bare": ("Dwale", "Aden", "Bare"),
    "Ethuro, David Ethwee": ("Ethuro", "David", "Ethwee"),
    "Farah, Maalim": ("Farah", "Maalim", ""),
    "Gaichuhie, Nelson Ributhi": ("Gaichuhie", "Nelson", "Ributhi"),
    "Ganya, Chachu Francis": ("Ganya", "Chachu", "Francis"),
    "Gesami, Ondicho James": ("Gesami", "Ondicho", "James"),
    "Gitau, Peter Njuguna": ("Gitau", "Peter", "Njuguna"),
    "Githae, Njeru Robinson": ("Githae", "Njeru", "Robinson"),
    "Githunguri, Stanley Munga": ("Githunguri", "Stanley", "Munga"),
    "Gitobu Imanyara": ("Imanyara", "Gitobu", ""),
    "Godhana, Gaddae Dhahado": ("Godhana", "Gaddae", "Dhahado"),
    "Gumbo, Nicholas Dr.": ("Gumbo", "Nicholas", "Dr."),
    "Gumo, Frederick Omulo": ("Gumo", "Frederick", "Omulo"),
    "Gunda, Fondo Benedict": ("Gunda", "Fondo", "Benedict"),
    "Haji, Yusuf": ("Haji", "Yusuf", ""),
    "Hassan, Ali Abdirahman": ("Hassan", "Ali", "Abdirahman"),
    "Imanyara, Gitobu": ("Imanyara", "Gitobu", ""),
    "Jeffah, Amason Kingi": ("Jeffah", "Amason", "Kingi"),
    "Jepkemoi, Sambili Hellen": ("Jepkemoi", "Sambili", "Hellen"),
    "Jirongo, Cyrus Khwa Shakhala": ("Jirongo", "Cyrus", "Khwa Shakhala"),
    "Joho, Ali Hassan": ("Joho", "Ali", "Hassan"),
    "Kabando, Wa Kabando": ("Kabando", "Wa", "Kabando"),
    "Kabogo, William Gitau": ("Kabogo", "William", "Gitau"),
    "Kaino, Kipchumba Boaz": ("Kaino", "Kipchumba", "Boaz"),
    "Kajembe, Ramadhan Seif": ("Kajembe", "Ramadhan", "Seif"),
    "Kajwang', Otieno Gerald": ("Kajwang'", "Otieno", "Gerald"),
    "Kamama, Abongotum, Asman": ("Kamama", "Abongotum", ", Asman"),
    "Kamar, Margaret Jepkoech": ("Kamar", "Margaret", "Jepkoech"),
    "Kamau, James Maina": ("Kamau", "James", "Maina"),
    "Kamau, Jamleck Irungu": ("Kamau", "Jamleck", "Irungu"),
    "Kapondi, Fred Chesebe": ("Kapondi", "Fred", "Chesebe"),
    "Kariuki, Ngata John": ("Kariuki", "Ngata", "John"),
    "Karua, Martha Wangari": ("Karua", "Martha", "Wangari"),
    "Kathuri, Emilio Mureithi": ("Kathuri", "Emilio", "Mureithi"),
    "Kazungu, Samuel Kambi": ("Kazungu", "Samuel", "Kambi"),
    "Kenneth, Peter": ("Kenneth", "Peter", ""),
    "Kenyatta, Uhuru Muigai": ("Kenyatta", "Uhuru", "Muigai"),
    "Keter, Charles Cheruiyot": ("Keter", "Charles", "Cheruiyot"),
    "Keya, Manyala Atanas": ("Keya", "Manyala", "Atanas"),
    "Keynan, Adnan Wehliye": ("Keynan", "Adnan", "Wehliye"),
    "Khalwale, Bonny (Dr.)": ("Khalwale", "Bonny", ""),
    "Khang'ati Alfred": ("Alfred", "Khang'ati", ""),
    "Khaniri, George Munyasia": ("Khaniri", "George", "Munyasia"),
    "Kibaki, Mwai Emilio": ("Kibaki", "Mwai", "Emilio"),
    "Kiema, Kilonzo Julius": ("Kiema", "Kilonzo", "Julius"),
    "Kigen, Luka Kipkorir": ("Kigen", "Luka", "Kipkorir"),
    "Kiilu, Peter L. N.": ("Kiilu", "Peter", "L. N."),
    "Kilimo, Linah Jebii": ("Kilimo", "Linah", "Jebii"),
    "Kilonzo, Charles Mutavi": ("Kilonzo", "Charles", "Mutavi"),
    "Kilonzo, Mutula": ("Kilonzo", "Mutula", ""),
    "Kimunya, Amos Muhinga": ("Kimunya", "Amos", "Muhinga"),
    "Kinyanjui, Lee Maiyani": ("Kinyanjui", "Lee", "Maiyani"),
    "Kioni, Jeremiah Ngayu": ("Kioni", "Jeremiah", "Ngayu"),
    "Kipkorir, William C": ("Kipkorir", "William", "C"),
    "Kiprono, Langat Magerer J": ("Kiprono", "Langat", "Magerer J"),
    "Kiptanui, Jackson Kiplagat": ("Kiptanui", "Jackson", "Kiplagat"),
    "Kipyegon, Julius Kones": ("Kipyegon", "Julius", "Kones"),
    "Kiuna, Joseph Nganga": ("Kiuna", "Joseph", "Nganga"),
    "Kiunjuri, Mwangi Festus": ("Kiunjuri", "Mwangi", "Festus"),
    "Kivuti, Lenny Maxwell": ("Kivuti", "Lenny", "Maxwell"),
    "Koech, David K": ("Koech", "David", "K"),
    "Koli, Nanok Josephat": ("Koli", "Nanok", "Josephat"),
    "Kones, Beatrice": ("Kones", "Beatrice", ""),
    "Kones, Kipkalya Kiprono": ("Kones", "Kipkalya", "Kiprono"),
    "Kosgey, Henry Kiprono": ("Kosgey", "Henry", "Kiprono"),
    "Kosgey, Sally Jemngetich": ("Kosgey", "Sally", "Jemngetich"),
    "Kuti, Mohammed Abdi (Dr.)": ("Kuti", "Mohammed", "Abdi"),
    "Kutuny, Joshua Serem": ("Kutuny", "Joshua", "Serem"),
    "Kyalo, Philip Kaloki (Prof.)": ("Kyalo", "Philip", "Kaloki"),
    "Laboso, Cherono Joyce Dr.": ("Laboso", "Cherono", "Joyce Dr."),
    "Laboso, Lorna Chepkemoi": ("Laboso", "Lorna", "Chepkemoi"),
    "Lagat, Elijah Kiptarbei": ("Lagat", "Elijah", "Kiptarbei"),
    "Lankas, Nkoidila Ole": ("Lankas", "Nkoidila", "Ole"),
    "Lekuton, Joseph": ("Lekuton", "Joseph", ""),
    "Lesirma, Simon Saimanga": ("Lesirma", "Simon", "Saimanga"),
    "Lessonet, Moses K": ("Lessonet", "Moses", "K"),
    "Letimalo, Raphael Lakalei": ("Letimalo", "Raphael", "Lakalei"),
    "Linturi, Mithika Franklin": ("Linturi", "Mithika", "Franklin"),
    "Litole, Wilson Mwotiny": ("Litole", "Wilson", "Mwotiny"),
    "Lugano, Charles Lilechi": ("Lugano", "Charles", "Lilechi"),
    "M'Mithiaru, Ntoitha": ("M'Mithiaru", "Ntoitha", ""),
    "Machage, Wilfred Gisuka (Dr.)": ("Machage", "Wilfred", "Gisuka"),
    "Magara, Omingo James": ("Magara", "Omingo", "James"),
    "Magwanga, Joseph Oyugi": ("Magwanga", "Joseph", "Oyugi"),
    "Mahmoud, Ali": ("Mahmoud", "Ali", ""),
    "Maina, Ephraim": ("Maina", "Ephraim", ""),
    "Maitha, Gideon Mungaro": ("Maitha", "Gideon", "Mungaro"),
    "Mathenge, Murugi Esther": ("Mathenge", "Murugi", "Esther"),
    "Mbai, Benson Itwiku": ("Mbai", "Benson", "Itwiku"),
    "Mbarire, Cecily Mutitu": ("Mbarire", "Cecily", "Mutitu"),
    "Mbau, Elias Peter": ("Mbau", "Elias", "Peter"),
    "Mbiuki, Japeth M Kereke": ("Mbiuki", "Japeth", "M Kereke"),
    "Mbuvi, Michael ": ("Mbuvi", "Michael", ""),
    "Michuki, John Njoroge": ("Michuki", "John", "Njoroge"),
    "Midiwo, Jakoyo Washington": ("Midiwo", "Jakoyo", "Washington"),
    "Mohamed, Hussein Ali": ("Mohamed", "Hussein", "Ali"),
    "Mohammed, Elmi Ibrahim": ("Mohammed", "Elmi", "Ibrahim"),
    "Monda, Robert Onsare": ("Monda", "Robert", "Onsare"),
    "Mudavadi, Musailia Wycliffe": ("Mudavadi", "Musailia", "Wycliffe"),
    "Mugo, Beth Wambui": ("Mugo", "Beth", "Wambui"),
    "Mungatana, Danson Buya": ("Mungatana", "Danson", "Buya"),
    "Munya, Peter Gatirau": ("Munya", "Peter", "Gatirau"),
    "Munyaka, Victor Kioko": ("Munyaka", "Victor", "Kioko"),
    "Munyes, John Kiyonga": ("Munyes", "John", "Kiyonga"),
    "Muoki, Isaac Mulatya": ("Muoki", "Isaac", "Mulatya"),
    "Muoki, Mutua Daniel": ("Muoki", "Mutua", "Daniel"),
    "Mureithi, Erastus Kihara": ("Mureithi", "Erastus", "Kihara"),
    "Murgor, Recha Julius": ("Murgor", "Recha", "Julius"),
    "Muriithi, Nderitu": ("Muriithi", "Nderitu", ""),
    "Muriuki, Silas Ruteere": ("Muriuki", "Silas", "Ruteere"),
    "Murungi, Kiraitu": ("Murungi", "Kiraitu", ""),
    "Musila, David": ("Musila", "David", ""),
    "Musyimi, Mutava": ("Musyimi", "Mutava", ""),
    "Musyoka, Kalonzo Stephen": ("Musyoka", "Kalonzo", "Stephen"),
    "Muthama, Johnson Nduya": ("Muthama", "Johnson", "Nduya"),
    "Mututho, John Michael N.": ("Mututho", "John", "Michael N."),
    "Mwadeghu, Thomas Ludindi": ("Mwadeghu", "Thomas", "Ludindi"),
    "Mwahima, Mashud Mwalimu": ("Mwahima", "Mashud", "Mwalimu"),
    "Mwaita, Sammy Silas Komen": ("Mwaita", "Sammy", "Silas Komen"),
    "Mwakulegwa, Danson Mwazo": ("Mwakulegwa", "Danson", "Mwazo"),
    "Mwakwere, Ali Chirau": ("Mwakwere", "Ali", "Chirau"),
    "Mwangi, Barnabas Muturi C": ("Mwangi", "Barnabas", "Muturi C"),
    "Mwatela, Calyst Andrew": ("Mwatela", "Calyst", "Andrew"),
    "Mwathi, Peter Mungai": ("Mwathi", "Peter", "Mungai"),
    "Mwau, John Harun": ("Mwau", "John", "Harun"),
    "Mwaura, David Njuguna Kiburi": ("Mwaura", "David", "Njuguna Kiburi"),
    "Mwiria, Kilemi Valerian": ("Mwiria", "Kilemi", "Valerian"),
    "Mwiru, Alex Muthengi Mburi": ("Mwiru", "Alex", "Muthengi Mburi"),
    "Namwamba, Ababu Tawfiq Pius": ("Namwamba", "Ababu", "Tawfiq Pius"),
    "Ndambuki, Gideon Musyoka": ("Ndambuki", "Gideon", "Musyoka"),
    "Ndeti, Wavinya": ("Ndeti", "Wavinya", ""),
    "Ng'ongo, Mbadi John": ("Ng'ongo", "Mbadi", "John"),
    "Ngilu, Charity Kaluki Mwendwa": ("Ngilu", "Charity", "Kaluki Mwendwa"),
    "Ngugi, Mwaniki David": ("Ngugi", "Mwaniki", "David"),
    "Nguyai, Lewis Nganga": ("Nguyai", "Lewis", "Nganga"),
    "Nkaissery, Joseph Kasaine": ("Nkaissery", "Joseph", "Kasaine"),
    "Nuh, Nassir Abdi": ("Nuh", "Nassir", "Abdi"),
    "Nyamai, Mutisya Charles": ("Nyamai", "Mutisya", "Charles"),
    "Nyambati, Enock Walter": ("Nyambati", "Enock", "Walter"),
    "Nyammo, Francis Thombe": ("Nyammo", "Francis", "Thombe"),
    "Nyong'o, Anyang' Peter (Prof.)": ("Nyong'o", "Anyang", "' Peter"),
    "Obure, Mogere Christopher": ("Obure", "Mogere", "Christopher"),
    "Odhiambo, Bwire Alfred": ("Odhiambo", "Bwire", "Alfred"),
    "Odinga, Oburu Ngona": ("Odinga", "Oburu", "Ngona"),
    "Odinga, Raila Amolo": ("Odinga", "Raila", "Amolo"),
    "Ogindo, Martin Otieno": ("Ogindo", "Martin", "Otieno"),
    "Ojaamongson, Sospeter Odeke": ("Ojaamongson", "Sospeter", "Odeke"),
    "Ojodeh, Joshua Orwa": ("Ojodeh", "Joshua", "Orwa"),
    "Ojwang, Cyprian Omollo": ("Ojwang", "Cyprian", "Omollo"),
    "Okemo, Chrysanthus": ("Okemo", "Chrysanthus", ""),
    "Ole Metito, Katoo": ("Ole Metito", "Katoo", ""),
    "Ole Ntimama, William Ronkorua": ("Ole Ntimama", "William", "Ronkorua"),
    "Olweny, Patrick Ayiecho (Prof.)": ("Olweny", "Patrick", "Ayiecho"),
    "Ombui, Moriasi Wilfred": ("Ombui", "Moriasi", "Wilfred"),
    "Ongeri, Kagengo Samson": ("Ongeri", "Kagengo", "Samson"),
    "Ongoro, Elizabeth": ("Ongoro", "Elizabeth", ""),
    "Onyancha, Charles": ("Onyancha", "Charles", ""),
    "Onyancha, Joel Omagwa": ("Onyancha", "Joel", "Omagwa"),
    "Onyonka, Momoima Richard": ("Onyonka", "Momoima", "Richard"),
    "Oparanya, Wycliffe Ambetsa": ("Oparanya", "Wycliffe", "Ambetsa"),
    "Orengo, James Aggrey": ("Orengo", "James", "Aggrey"),
    "Otieno, Dalmas Anyango": ("Otieno", "Dalmas", "Anyango"),
    "Ottichilo, Wilbur": ("Ottichilo", "Wilbur", ""),
    "Otuoma, Nyongesa Paul (Dr.)": ("Otuoma", "Nyongesa", "Paul"),
    "Outa, Frederick Otieno": ("Outa", "Frederick", "Otieno"),
    "Pesa, John Dache": ("Pesa", "John", "Dache"),
    "Pogisio, Samuel Losuron": ("Pogisio", "Samuel", "Losuron"),
    "Rai, Samuel Gonzi": ("Rai", "Samuel", "Gonzi"),
    "Rege, G Kwanya James": ("Rege", "G", "Kwanya James"),
    "Ruto, William K Samoei": ("Ruto", "William", "K Samoei"),
    "Rutto, Isaac Kiprono": ("Rutto", "Isaac", "Kiprono"),
    "Saitoti George (Prof.)": ("George ", "Saitoti", ""),
    "Sambu, Alfred Wekesa": ("Sambu", "Alfred", "Wekesa"),
    "Sasura, Abdi Tarry": ("Sasura", "Abdi", "Tarry"),
    "Sasura, Hussein Tarry": ("Sasura", "Hussein", "Tarry"),
    "Shaban, Naomi Namsi": ("Shaban", "Naomi", "Namsi"),
    "Shabir, Shekeel Ahmed": ("Shabir", "Shekeel", "Ahmed"),
    "Shitanda, Soita Peter": ("Shitanda", "Soita", "Peter"),
    "Simiyu, Eseli David": ("Simiyu", "Eseli", "David"),
    "Sugow, Aden": ("Sugow", "Aden", ""),
    "Swaleh, Swaleh": ("Swaleh", "Swaleh", ""),
    "Thuo, George": ("Thuo", "George", ""),
    "Too, David Kimutai": ("Too", "David", "Kimutai"),
    "Twaha, Fahim Yasin": ("Twaha", "Fahim", "Yasin"),
    "Waibara, Kungu Clement": ("Waibara", "Kungu", "Clement"),
    "Waititu, Ferdinand": ("Waititu", "Ferdinand", ""),
    "Wakoli, Bifwoli Sylvester": ("Wakoli", "Bifwoli", "Sylvester"),
    "Wamalwa, Eugene Ludovic": ("Wamalwa", "Eugene", "Ludovic"),
    "Wambugu, Clement Muchiri": ("Wambugu", "Clement", "Muchiri"),
    "Warugongo, Nemesyus": ("Warugongo", "Nemesyus", ""),
    "Washiali, Jomo Benjamin": ("Washiali", "Jomo", "Benjamin"),
    "Wathika, Dickson Mwangi": ("Wathika", "Dickson", "Mwangi"),
    "Wekesa, Noah Mahalang'ang'a (Dr.)": ("Wekesa", "Noah", "Mahalang'ang'a"),
    "Were, Aoko David": ("Were", "Aoko", "David"),
    "Were, Melitus Mugabe": ("Were", "Melitus", "Mugabe"),
    "Wetangula, Moses Masika": ("Wetangula", "Moses", "Masika"),
    "Yinda, Edwin Ochieng": ("Yinda", "Edwin", "Ochieng"),
    "Zonga, Omar Mbwana": ("Zonga", "Omar", "Mbwana"),

    "Abdullahi, Dahir Sheik"            : ("Abdullahi","Dahir","Sheik"          )         ,
    "Dzoro, Morris Mwachondo"           : ("Dzoro","Morris","Mwachondo"         )         ,
    "Gachagua, Nderitu James"           : ("Gachagua", "Nderitu", "James"         )       ,
    "Gachara, Geoffrey Muchiri"         : ("Gachara", "Geoffrey", "Muchiri"       )       ,
    "Gitura, Kembi"                     : ("Gitura", "", "Kembi"                   )      ,
    "Godana, Bonaya"                    : ("Godana", "Bonaya"  , ""                )      ,
    "Hussein, Mohammed"                 : ("Hussein", "Mohammed"   , ""            )      ,
    "Kagwe, Mutahi"                     : ("Kagwe", "Mutahi"   , ""                )      ,
    "Kamanda, Maina"                    : ("Kamanda", "Maina"  , ""                )      ,
    "Kamotho, Joseph John"              : ("Kamotho", "Joseph", "John"            )       ,
    "Karaba, Daniel Dickson"            : ("Karaba", "Daniel", "Dickson"          )       ,
    "Karue, Muriuki"                    : ("Karue", "Muriuki"      , ""            )      ,
    "Karume, Njenga J"                  : ("Karume", "Njenga", "J"                )       ,
    'Khamisi, Joseph "Joe" Matano'      : ("Khamisi", 'Joseph', '"Joe" Matano'    )       ,
    "Kimathi, Viscount"                 : ("Kimathi", "Viscount"       , ""        )      ,
    "Kingi, Joseph Kahindi"             : ("Kingi", "Joseph", "Kahindi"           )       ,
    "Kombe , Harrison Garama"           : ("Kombe", "Harrison", "Garama"         )        ,
    "Kombo, Musikari"                   : ("Kombo", "Musikari"            , ""     )      ,
    "Kuria, Kanyingi Simeon"            : ("Kuria", "Kanyingi", "Simeon"          )       ,
    "Maathai, Wangari (Prof.)"          : ("Maathai", "Wangari", ""        )              ,
    "Madoka, Marsden Herman"            : ("Madoka", "Marsden", "Herman"          )       ,
    "Magugu, Arthur"                    : ("Magugu", "Arthur", ""                  )      ,
    "Maitha, Lucas"                     : ("Maitha", "Lucas", ""                   )      ,
    "Mganga, Boniface"                  : ("Mganga", "Boniface", ""                )      ,
    "Mgangha, Mwandawiro"               : ("Mgangha", "Mwandawiro", ""             )      ,
    "Muiruri, Patrick"                  : ("Muiruri", "Patrick", ""                )      ,
    "Muite, Paul Kibugi"                : ("Muite", "Paul", "Kibugi"              )       ,
    "Muriithi, P G"                     : ("Muriithi", "P G", ""                   )      ,
    "Murungaru, Christopher Ndarathi"   : ("Murungaru", "Christopher", "Ndarathi" )       ,
    "Muturi, Justin"                    : ("Muturi", "Justin", ""                  )      ,
    "Mwaboza, Anania"                   : ("Mwaboza", "Anania", ""                 )      ,
    "Mwangi, Onesmus"                   : ("Mwangi", "Onesmus", ""                 )      ,
    "Mwenje, David"                     : ("Mwenje", "David", ""                   )      ,
    "Nderitu, Alfred Mwangi"            : ("Nderitu", "Alfred", "Mwangi"          )       ,
    "Ndolo, Reuben"                     : ("Ndolo", "Reuben", ""                   )      ,
    "Ngozi, Abdallah"                   : ("Ngozi", "Abdallah", ""                 )      ,
    "Nyagah, Norman"                    : ("Nyagah", "Norman", ""                  )      ,
    "Omondi, William"                   : ("Omondi", "William", ""                 )      ,
    "Owidi, Peter Otieno"               : ("Owidi", "Peter", "Otieno"             )       ,
    "Paddy Ahenda"                      : ("Ahenda","Paddy", ""                    )      ,
    "Salat, Nick"                       : ("Salat", "Nick", ""                     )      ,
    "Shakombo, Rashid"                  : ("Shakombo", "Rashid", ""                )      ,
    "Tola, Kofa Mugava"                 : ("Tola", "Kofa", "Mugava"               )       ,
    "Toro, Joshua Ngugi"                : ("Toro", "Joshua", "Ngugi"              )       ,
    "Waithaka, Mwangi Kirika"           : ("Waithaka", "Mwangi", "Kirika"         )       ,
    "Wario, Ali"                        : ("Wario", "Ali", ""                      )      ,
    "Kerrow, Billow": ("Kerrow", "Billow", ""),
    "Mohamed, Abdi Haji Mohamed": ("Mohamed", "Abdi", "Haji Mohamed"),
    "Shaban, Isack": ("Shaban", "Isack", ""),
    "Ibrahim, Ali Abdullahi": ("Ibrahim", "Ali", "Abdullahi"),
    "Khalif, Ahmad Muhammad": ("Khalif", "Ahmad", "Muhammad"),
    "Mohammed, A M": ("Mohammed", "A", "M"),
    "[None]": ("", "[None]", ""),
    "Kaindi, Peter Kyalo": ("Kaindi", "Peter", "Kyalo"),
    "Mwanzia, Daudi": ("Mwanzia", "Daudi", ""),
    "Nyagah, Joseph William N": ("Nyagah", "Joseph", "William N"),
    "Muriungi, Raphael": ("Muriungi", "Raphael", ""),
    "M'Mukindia, Kirugi": ("M'Mukindia", "Kirugi", ""),
    "Ndile, Kalembe Richard N.": ("Ndile", "Kalembe", "Richard N."),
    "Mutiso, Mutinda": ("Mutiso", "Mutinda", ""),
    "Ivuti, Patrice Ezekiel Mwangu": ("Ivuti", "Patrice", "Ezekiel Mwangu"),
    "Mwendwa, Nyiva": ("Mwendwa", "Nyiva", ""),
    "Ngoyoni, Titus Lemusei": ("Ngoyoni", "Titus", "Lemusei"),
    "Kibwana Kivutha (Prof.)": ("Kivutha ", "Kibwana", ""),
    "Ndwiga, Njeru Peter": ("Ndwiga", "Njeru", "Peter"),
    "Munyao, Joseph Konzolo": ("Munyao", "Joseph", "Konzolo"),
    "Galgalo, Boru Gurach": ("Galgalo", "Boru", "Gurach"),
    "Katuku, Mutua John": ("Katuku", "Mutua", "John"),
    "M'Nkiria, P.S.M": ("M'Nkiria", "P", ".S.M"),
    "Mwiraria, David": ("Mwiraria", "David", ""),
    "Maore, Maoka Richard": ("Maore", "Maoka", "Richard"),
    "Nyaga, Wambora Martin": ("Nyaga", "Wambora", "Martin"),
    "Kagwima, Francis Nyamu": ("Kagwima", "Francis", "Nyamu"),
    "Wanjala, Raphael": ("Wanjala", "Raphael", ""),
    "Mango, Christine (Prof.)": ("Mango", "Christine", ""),
    "Marende, Kenneth Otiato": ("Marende", "Kenneth", "Otiato"),
    "Awori, Arthur 'Moody' Mudeyi": ("Awori", "Arthur", "'Moody' Mudeyi"),
    "Wamunyinyi, Wafula, A.M": ("Wamunyinyi", "Wafula", ", A.M"),
    "Arungah, J.O": ("Arungah", "J", ".O"),
    "Kituyi, Mukhisa (Dr.)": ("Kituyi", "Mukhisa", ""),
    "Kibunguchy, Enoch (Dr.)": ("Kibunguchy", "Enoch", ""),
    "Kulundu, Newton (Dr.)": ("Kulundu", "Newton", ""),
    "Were, David Aoko": ("Were", "David", "Aoko"),
    "Serut, John": ("Serut", "John", ""),
    "Osundwa, Wycliffe Wilson": ("Osundwa", "Wycliffe", "Wilson"),
    "Akaranga, Moses (Rev.)": ("Akaranga", "Moses", ""),
    "Khamasi, Daniel Lyula": ("Khamasi", "Daniel", "Lyula"),
    "Ligale, Andrew N. N.": ("Ligale", "Andrew", "N. N."),
    "Too (Arap), Noah": ("Too ", "Noah", ""),
    "Choge, Jimmy": ("Choge", "Jimmy", ""),
    "Weya, Sammy": ("Weya", "Sammy", ""),
    "Moi, Gideon": ("Moi", "Gideon", ""),
    "Boit, William": ("Boit", "William", ""),
    "Monati, S K": ("Monati", "S", "K"),
    "Zebedeo, John Opore": ("Zebedeo", "John", "Opore"),
    "Kipkorir, Sang Marisin Paul": ("Kipkorir", "Sang", "Marisin Paul"),
    "Koech, John Kipsang": ("Koech", "John", "Kipsang"),
    "Kirwa, Kipruto Rono": ("Kirwa", "Kipruto", "Rono"),
    "Sirma, Musa": ("Sirma", "Musa", ""),
    "Lagat, Joseph Kipchumba": ("Lagat", "Joseph", "Kipchumba"),
    "Koros, David Kiptanui": ("Koros", "David", "Kiptanui"),
    "Tarus, Stephen Kipkiyeny": ("Tarus", "Stephen", "Kipkiyeny"),
    "Syon'goh, Zaddock Madiri": ("Syon'goh", "Zaddock", "Madiri"),
    "Moroto, Samuel Chumel": ("Moroto", "Samuel", "Chumel"),
    "Awiti, Paul Adhu (Dr.)": ("Awiti", "Paul", "Adhu"),
    "Kipkosgei, Lucas Chepkitony": ("Kipkosgei", "Lucas", "Chepkitony"),
    "Biwott, Nicholas Kipyator": ("Biwott", "Nicholas", "Kipyator"),
    "Konchellah, Gideon Sitelu": ("Konchellah", "Gideon", "Sitelu"),
    "Rutto, Sammy (Dr.)": ("Rutto", "Sammy", ""),
    "Sungu, Eric Gor": ("Sungu", "Eric", "Gor"),
    "Nyagudi, Ken (Rev.)": ("Nyagudi", "Ken", ""),
    "Angwenyi, Jimmy Nuru Ondieki": ("Angwenyi", "Jimmy", "Nuru Ondieki"),
    "Nyang'au, Samson Okioma": ("Nyang'au", "Samson", "Okioma"),
    "Cheruiyot, Sammy Koech": ("Cheruiyot", "Sammy", "Koech"),
    "Cheboi, Moses Kipketiboi": ("Cheboi", "Moses", "Kipketiboi"),
    "Kariuki, G.G": ("Kariuki", "G", ".G"),
    "Sudi, David Kiprono Sutter": ("Sudi", "David", "Kiprono Sutter"),
    "Owino, Likowa": ("Owino", "Likowa", ""),
    "Kipkaptor, Joseph Korir": ("Kipkaptor", "Joseph", "Korir"),
    "Macharia, Mukiri": ("Macharia", "Mukiri", ""),
    "Sambu, John Kipkorir": ("Sambu", "John", "Kipkorir"),
    "Kihara, Jayne": ("Kihara", "Jayne", ""),
    "Kariuki, Mirugi": ("Kariuki", "Mirugi", ""),
    "Ole Ntutu, Stephen K.": ("Ole Ntutu", "Stephen", "K."),
    "Masanya, Godfrey Okeri": ("Masanya", "Godfrey", "Okeri"),
    "Odoyo, Peter Ochieng'": ("Odoyo", "Peter", "Ochieng'"),
    "Nyamunga, Eric Opon": ("Nyamunga", "Eric", "Opon"),
    "Nyachae, Simeon": ("Nyachae", "Simeon", ""),
    "Ogur, Tobias Ochola": ("Ogur", "Tobias", "Ochola"),
    "Okundi, Philip": ("Okundi", "Philip", ""),
    "Tuju, Raphael": ("Tuju", "Raphael", ""),
    "Chelaite, Alicen Jematia": ("Chelaite", "Alicen", "Jematia"),
    "Ayacko, Ochilo Mbogo George": ("Ayacko", "Ochilo", "Mbogo George"),
    "Nakitare, Davis": ("Nakitare", "Davis", ""),
    "Leshore, Sammy Pirisa": ("Leshore", "Sammy", "Pirisa"),
    "Ruto, Phillip Rotino": ("Ruto", "Phillip", "Rotino"),
    "Kimetto, Anthony": ("Kimetto", "Anthony", ""),
    "Wamwere, Koigi": ("Wamwere", "Koigi", ""),
    "Ewoton, Francis Achuka": ("Ewoton", "Francis", "Achuka"),
    "Ondiek, Stephen": ("Ondiek", "Stephen", ""),
    "Odhiambo, Herman Omamba": ("Odhiambo", "Herman", "Omamba"),
    "Obwocha, Henry": ("Obwocha", "Henry", ""),
    "Ali, Amina Abdalla": ("Ali", "Amina", "Abdalla"),
    "Aringo, Oloo Peter Castro": ("Aringo", "Oloo", "Peter Castro"),
    "Keino, Esther Cherono (Dr.)": ("Keino", "Esther", "Cherono"),
    "Mwau, Adelina Ndeto": ("Mwau", "Adelina", "Ndeto"),
    "Ndung'u, Njoki Susanna": ("Ndung'u", "Njoki", "Susanna"),
    "Ojiambo, Julia": ("Ojiambo", "Julia", ""),
    "Oniang'o, Ruth (Prof.)": ("Oniang'o", "Ruth", ""),
    "Tett, Betty Njeri": ("Tett", "Betty", "Njeri"),
    "Ole Kaparo, Francis Xavier": ("Ole Kaparo", "Francis", "Xavier"),
    "Wako, Amos": ("Wako", "Amos", ""),
    "Mirugi, Kariuki William": ("Mirugi", "Kariuki", "William"),
    "Galgalo, Wario Malla": ("Galgalo", "Wario", "Malla"),
    "Yattani, Ukur Kanacho": ("Yattani", "Ukur", "Kanacho"),
    "Maitha, Moffat Muia": ("Maitha", "Moffat", "Muia"),
    "Petkay Miriti": ("Miriti", "Petkay", ""),
    "Wanjiru, Margaret (Bishop)": ("Wanjiru", "Margaret", ""),
    "Mahmoud, Maalim Mohamed": ("Mahmoud", "Maalim", "Mohamed"),
    "Kereke, Japeth M": ("Kereke", "Japeth", "M"),
    "Noor, Sophia Abdi": ("Noor", "Sophia", "Abdi"),
    "Odhiambo, Millie Grace Akoth": ("Odhiambo", "Millie", "Grace Akoth"),
    "Shabesh, Racheal Wambui": ("Shabesh", "Racheal", "Wambui"),
    "Yakub, Muhamad Dory Mohamad": ("Yakub", "Muhamad", "Dory Mohamad"),
    "Leshomo, Maison": ("Leshomo", "Maison", ""),
    "Abdalla, Shakila": ("Abdalla", "Shakila", ""),
    "Affey, Mohamed Abdi": ("Affey", "Mohamed", "Abdi"),
    "Abdalla, Amina": ("Abdalla", "Amina", ""),
    "Nyamweya, George Omari": ("Nyamweya", "George", "Omari"),
    "Benjamin Langat": ("Langat", "Benjamin", ""),
}
