#!/usr/bin/env python

import os
import sys

# Horrible boilerplate - there must be a better way :)
sys.path.append(
    os.path.abspath(
        os.path.dirname(__file__) + '../../..'
    ),
),


from django.utils.text import slugify

from pombola.core import models


constituency_renames = [
    #    ( "From", "To" ),
    ( "Mukurweni", "Mukurweini" ),
    ( "Ol' Kalou", "Ol Kalou" ),
    ( "Kisumi Rural", "Kisumu Rural" ),
    ( "Kisumi Town East", "Kisumu Town East" ),
    ( "Kisumi Town West", "Kisumu Town West" ),
    ( "Cherengani", "Cherangany" ),
    ( "Loitokitok", "Kajiado South" ),
]

for from_to in constituency_renames:
    ( from_name, to_name ) = from_to

    try:
        place = models.Place.objects.get(name=from_name)
    except models.Place.DoesNotExist:
        continue

    print "Renaming '%s' to '%s'" % (from_name, to_name)
    place.name = to_name
    place.save()


# names = [
#     ("Dagoretti", "Beth", "Wambui", "Mugo" ),
#     ("Embakasi", "Ferdinand", "Ndung'u", "Waititu" ),
#     ("Kasarani", "Elizabeth", "", "Ongoro" ),
#     ("Langata", "Raila", "Amolo", "Odinga" ),
#     ("Makadara", "Dickson", "Mwangi", "Wathika" ),
#     ("Starehe", "Margaret", "Wanjiru", "Kariuki" ),
#     ("Westlands", "Fred", "Omulo", "Gumo" ),
#     ("Kamukunji", "Simon", "Ng'ang'a", "Mbugua" ),
#     ("Gatanga", "Peter", "", "Kenneth" ),
#     ("Gatundu North", "Clement", "Kung'u", "Waibara" ),
#     ("Gatundu South", "Uhuru", "Muigai", "Kenyatta" ),
#     ("Gichugu", "Martha", "Wangari", "Karua" ),
#     ("Githunguri", "Peter", "Njoroge", "Baiya" ),
#     ("Juja", "George", "", "Thuo" ),
#     ("Kandara", "James", "Maina", "Kamau" ),
#     ("Kangema", "John", "Michuki", "Njoroge" ),
#     ("Kiambaa", "Stanley", "Munga", "Githunguri" ),
#     ("Kieni", "Nemesius", "", "Warugongo" ),
#     ("Kigumo", "Jamleck", "Irungu", "Kamau" ),
#     ("Kiharu", "Barnabas", "Muturi C.", "Mwangi" ),
#     ("Kikuyu", "Lewis", "Nguyai", "Nganga" ),
#     ("Kinangop", "David", "Mwaniki", "Ngugi" ),
#     ("Kipipiri", "Amos", "Muhinga", "Kimunya" ),
#     ("Kirinyaga Central", "John", "Ngata", "Kariuki" ),
#     ("Lari", "David", "Njuguna Kiburi", "Mwaura" ),
#     ("Limuru", "Peter", "Mungai", "Mwathi" ),
#     ("Maragwa", "Peter", "Elias", "Mbau" ),
#     ("Mathioya", "Clement", "Muchiri", "Wambugu" ),
#     ("Mathira", "Ephraim", "Mwangi", "Maina" ),
#     ("Mukurweini", "Kabando", "wa", "Kabando" ),
#     ("Mwea", "Peter", "Njuguna", "Gitau" ),
#     ("Ndaragwa", "Jeremiah", "Ngayu", "Kioni" ),
#     ("Ndia", "Robinson", "Njeru", "Githae" ),
#     ("Nyeri Town", "Esther", "Murugi", "Mathenge" ),
#     ("Ol Kalou", "Erastus", "Kihara", "Mureithi" ),
#     ("Othaya", "Mwai", "Emilio", "Kibaki" ),
#     ("Tetu", "Francis", "Thombe", "Nyammo" ),
#     ("Central Imenti", "Gitobu", "", "Imanyara" ),
#     ("Gachoka", "Mutava", "", "Musyimi" ),
#     ("Igembe North", "Ntoitha", "", "M'mithiaru" ),
#     ("Igembe South", "Franklin", "Mithika", "Linturi" ),
#     ("Isiolo North", "Mohammed", "Abdi", "Kuti" ),
#     ("Isiolo South", "Abdul", "Bahari", "Ali" ),
#     ("Kaiti", "Gideon", "Musyoka", "Ndambuki" ),
#     ("Kangundo", "Johnson", "Nduya", "Muthama" ),
#     ("Kathiani", "Ndeti", "", "Wavinya" ),
#     ("Kibwezi", "Philip", "Kyalo", "Kaloki" ),
#     ("Kilome", "John", "Harun", "Mwau" ),
#     ("Kitui Central", "Charity", "Kaluki", "Ngilu" ),
#     ("Kitui South", "Issac", "Mulatya", "Muoki" ),
#     ("Kitui West", "Charles", "Mutisya", "Nyamai" ),
#     ("Laisamis", "Joseph", "Lemasolai", "Lekuton" ),
#     ("Machakos Town", "Victor", "Kioko", "Munyaka" ),
#     ("Makueni", "Peter", "L. N.", "Kiilu" ),
#     ("Manyatta", "Emillio", "Mureithi", "Kathuri" ),
#     ("Masinga", "Benson", "Mbai", "Itwiku" ),
#     ("Mbooni", "Mutula", "", "Kilonzo" ),
#     ("Moyale", "Mohamud", "Mohammed", "Ali" ),
#     ("Mutito", "Julius", "Kiema", "Kilonzo" ),
#     ("Mwala", "Daniel", "Mutua", "Muoki" ),
#     ("Mwingi North", "Stephen", "Kalonzo", "Musyoka" ),
#     ("Mwingi South", "David", "", "Musila" ),
#     ("Nithi", "Japhet", "M. Kareke", "Mbiuki" ),
#     ("North Horr", "Francis", "Chachu", "Ganya" ),
#     ("North Imenti", "Silas", "Muriuki", "Ruteere" ),
#     ("Runyenjes", "Cecily", "Mutitu", "Mbarire" ),
#     ("Saku", "Hussein", "Tarry", "Sasura" ),
#     ("Siakago", "Lenny", "Maxwell", "Kivuti" ),
#     ("South Imenti", "Kiraitu", "", "Murungi" ),
#     ("Tharaka", "Alex", "Muthengi Mburi", "Mwiru" ),
#     ("Tigania East", "Peter", "Gatirau", "Munya" ),
#     ("Tigania West", "Valerian", "Kalemi", "Mwiria" ),
#     ("Yatta", "Charles", "Mutavi", "Kilonzo" ),
#     ("Amagoro", "Ojaamongson", "Sospeter", "Odeke" ),
#     ("Budalangi", "Pius", "Tawfiq Namwamba", "Ababu" ),
#     ("Bumula", "Sylvester", "Wakoli", "Bifwoli" ),
#     ("Butere", "Wycliffe", "", "Oparanya" ),
#     ("Butula", "Bwire", "Alfred", "Odhiambo" ),
#     ("Emuhaya", "Wilbur", "Ottichilo", "" ),
#     ("Funyula", "Otuoma", "Paul", "Nyogesa" ),
#     ("Hamisi", "George", "", "khaniri" ),
#     ("Ikolomani", "Bonny", "", "Khalwale" ),
#     ("Kanduyi", "Alfred", "", "Khang'ati" ),
#     ("Khwisero", "Evans", "", "Akula" ),
#     ("Kimilili", "David", "Eseli", "Simiyu" ),
#     ("Lugari", "Cyrus", "", "Jirongo" ),
#     ("Lurambi", "Atanas", "", "Keya" ),
#     ("Malava", "Soita", "", "Shitanda" ),
#     ("Matungu", "David", "", "Were" ),
#     ("Mt Elgon", "Fred", "", "Kapondi" ),
#     ("Mumias", "Benjamin", "Jomo", "Washiali" ),
#     ("Nambale", "Chrysanthus", "", "Okemo" ),
#     ("Sabatia", "Musalia", "", "Mudavadi" ),
#     ("Shinyalu", "Justus", "Kizito", "Mugali" ),
#     ("Sirisia", "Moses", "", "Wetangula" ),
#     ("Vihiga", "Yusuf", "Kifuma", "Chanzu" ),
#     ("Webuye", "Alfred", "", "Sambu" ),
#     ("Alego", "Edwin", "Ochieng", "Yinda" ),
#     ("Bobasi", "Christopher", "Mogere", "Obure" ),
#     ("Bomachoge", "Joel", "", "Onyancha" ),
#     ("Bonchari", "Charles", "", "Onyancha" ),
#     ("Bondo", "Oburu", "", "Odinga" ),
#     ("Gem", "Washington", "Jakoyo", "Midiwo" ),
#     ("Gwassi", "Mbadi", "John", "Ng'ongo" ),
#     ("Karachuonyo", "James", "Kwanya", "Rege" ),
#     ("Kasipul Kabondo", "Joseph", "Oyugi", "Magwanga" ),
#     ("Kisumu Rural", "Peter", "Anyang'", "Nyong'o" ),
#     ("Kisumu Town East", "Ahmed", "Shakeel Shabbir", "Ahmed" ),
#     ("Kisumu Town West", "John", "Olago", "Aluoch" ),
#     ("Kitutu Chache", "Richard", "", "Momoima" ),
#     ("Kitutu Masaba", "Walter", "Enock Nyambati", "Osebe" ),
#     ("Kuria", "Wilfred", "Gisuka", "Machage" ),
#     ("Mbita", "Gerald", "Otieno", "Kajwang" ),
#     ("Migori", "John", "Pesa", "Dache" ),
#     ("Muhoroni", "Patrick", "Ayiecho", "Olweny" ),
#     ("Ndhiwa", "Joshua", "Orwa", "Ojodeh" ),
#     ("North Mugirango Borabu", "Moriasi", "Wilfred", "Ombui" ),
#     ("Nyakach", "Pollyins", "Ochieng", "Anyango" ),
#     ("Nyando", "Frederick", "Outa", "Otieno" ),
#     ("Nyaribari Chache", "Robert", "Onsare", "Monda" ),
#     ("Nyaribari Masaba", "Samson", "Kagengo", "Ongeri" ),
#     ("Nyatike", "Peter", "Edick Omondi", "Anyanga" ),
#     ("Rangwe", "Martin", "Otieno", "Ogindo" ),
#     ("Rarieda", "Nicholas", "", "Gumbo" ),
#     ("Rongo", "Dalmas", "Anyango", "Otieno" ),
#     ("South Mugirango", "James", "Omingo", "Magara" ),
#     ("Ugenya", "James", "", "Orengo" ),
#     ("Uriri", "Cyprian", "Ojwang", "Omollo" ),
#     ("West Mugirango", "James", "Ondicho", "Gesami" ),
#     ("Bahari", "Benedict", "Fondo", "Gunda" ),
#     ("Bura", "Abdi", "Nassir", "Nuh" ),
#     ("Changamwe", "Ramadhan", "Seif", "Kajembe" ),
#     ("Galole", "Dhadho", "Gaddae", "Goghana" ),
#     ("Ganze", "Francis", "S. K.", "Baya" ),
#     ("Garsen", "Danson", "Buya", "Mungatana" ),
#     ("Kaloleni", "Samwel", "Kazungu", "Kambi" ),
#     ("Kinango", "Samuel", "Gonzi", "Rai" ),
#     ("Kisauni", "Hassan", "Ali", "Joho" ),
#     ("Lamu East", "Abu", "Mohamed", "Chiaba" ),
#     ("Lamu West", "Yasin", "Fahim", "Twaha" ),
#     ("Likoni", "Mwalimu", "Masudi", "Mwahima" ),
#     ("Magarini", "Amason", "Kingi", "Jeffah" ),
#     ("Malindi", "Maitha", "Gideon", "Mung'aro" ),
#     ("Matuga", "Ali", "Chirau", "Mwakwere" ),
#     ("Msambweni", "Omar", "Mbwana", "Zonga" ),
#     ("Mvita", "Najib", "Mohamed", "Balala" ),
#     ("Mwatate", "Calist", "Andrew", "Mwatela" ),
#     ("Taveta", "Naomi", "Namisi", "Shaban" ),
#     ("Voi", "Danson", "Mwazo", "Mwakulegwa" ),
#     ("Wundanyi", "Thomas", "Luhindi", "Mwadeghu" ),
#     ("Ainamoi", "David", "Kimutai", "Too" ),
#     ("Aldai", "Sally", "", "Kosgey" ),
#     ("Baringo Central", "Sammy", "", "Mwaita" ),
#     ("Baringo East", "Kamama", "Asman", "Abongutum" ),
#     ("Baringo North", "William", "", "Kipkorir" ),
#     ("Belgut", "Charles", "Cheruiyot", "Keter" ),
#     ("Bomet", "Kipkalya", "", "Kones" ),
#     ("Bureti", "Franklin", "", "Bett" ),
#     ("Chepalungu", "Isaac", "", "Ruto" ),
#     ("Cherangany", "Joshua", "", "Kutuny" ),
#     ("Eldama Ravine", "Moses", "", "Lessonet" ),
#     ("Eldoret East", "Kamar", "Margret", "Jepkoech" ),
#     ("Eldoret North", "William", "", "Ruto" ),
#     ("Eldoret South", "Peris", "", "Chepchumba" ),
#     ("Emgwen", "Elijah", "", "Lagat" ),
#     ("Kacheliba", "Samuel", "", "Poghisio" ),
#     ("Kajiado Central", "Joseph", "Ole", "Nkaissery" ),
#     ("Kajiado North", "George", "", "Saitoti" ),
#     ("Kapenguria", "Julius", "", "Mugor" ),
#     ("Keiyo North", "Chepkitony", "Lucas", "Kipkosei" ),
#     ("Keiyo South", "Kiptanui", "Kiplagat", "Jackson" ),
#     ("Kipkelion", "Kiprono", "", "Langat" ),
#     ("Konoin", "Julius", "Kipyegon", "Kones" ),
#     ("Kuresoi", "Zakayo", "", "Cheroiyot" ),
#     ("Kwanza", "Noah", "", "Wakesa" ),
#     ("Laikipia East", "Kiunjuri", "Festus", "Mwangi" ),
#     ("Laikipia West", "Muriithi", "", "Nderitu" ),
#     ("Kajiado South", "Katoo", "Ole", "Metito" ),
#     ("Marakwet East", "Linah", "", "Kilimo" ),
#     ("Marakwet West", "Kaino", "Boaz", "Kipchuma" ),
#     ("Mogotio", "Hellen", "", "Sambili" ),
#     ("Molo", "Joseph", "Nganga", "Kiuna" ),
#     ("Mosop", "David", "", "Koech" ),
#     ("Naivasha", "John", "Michael Njenga", "Mututho" ),
#     ("Nakuru Town", "Lee", "Maiyani", "Kinyanjui" ),
#     ("Narok North", "William", "Ronkorua", "Ntimama" ),
#     ("Narok South", "Nkoidilla", "", "Lankas" ),
#     ("Rongai", "Kigen", "Luka", "Kipkorir" ),
#     ("Saboti", "Eugene", "Ludovic", "Wamalwa" ),
#     ("Samburu East", "Raphael", "", "Lentimalo" ),
#     ("Samburu West", "Simon", "", "Lesirma" ),
#     ("Sigor", "Wilson", "", "Litole" ),
#     ("Sotik", "Lorna", "", "Laboso" ),
#     ("Subukia", "Nelson", "", "Gaichuhie" ),
#     ("Tinderet", "Henry", "Kiprono", "Kosgey" ),
#     ("Turkana Central", "David", "", "Ethuro" ),
#     ("Turkana North", "John", "", "Munyes" ),
#     ("Turkana South", "Josephat", "Koli", "Nanok" ),
#     ("Dujis", "Bare", "Aden", "Duale" ),
#     ("Fafi", "Ahmed", "Aden", "Sugow" ),
#     ("Ijara", "Mohamed", "Yussuf", "Haji" ),
#     ("Lagdera", "Farah", "", "Maalim" ),
#     ("Mandera Central", "Hussein", "Mohammed", "Abdikadir" ),
#     ("Mandera East", "Mohamed", "Hussein", "Ali" ),
#     ("Mandera West", "Mohamud", "Maalim", "Mohamed" ),
#     ("Wajir East", "Ibrahim", "Elmi", "Mohamed" ),
#     ("Wajir South", "Abdirahman", "Ali", "Hassan" ),
#     ("Wajir West", "Adan", "Keynan", "Wehliye" ),
# ]
#
#
# for name in names:
#     (constituency, first, middle, last ) = name
#
#     place = models.Place.objects.get(name=constituency)
#
#     mps = [ i.person for i in place.position_set.filter( title__slug='mp' )]
#
#     for mp in mps:
#         print ( constituency, mp.id, mp.name, first, middle, last )


renames = [
    ('Ainamoi', 212, u'David Too', 'David', 'Kimutai', 'Too'),
    ('Aldai', 59, u'Sally Kosgey', 'Sally', '', 'Kosgey'),
    ('Alego', 154, u'Edwin Yinda', 'Edwin', 'Ochieng', 'Yinda'),
    ('Amagoro', 196, u'Sospeter Ojaamongson', 'Ojaamongson', 'Sospeter', 'Odeke'),
    ('Bahari', 25, u'Fondo Gunda', 'Benedict', 'Fondo', 'Gunda'),
    ('Baringo Central', 100, u'Sammy Mwaita', 'Sammy', '', 'Mwaita'),
    ('Baringo East', 165, u'Abongotum Kamama', 'Kamama', 'Asman', 'Abongutum'),
    ('Baringo North', 50, u'William Kipkorir', 'William', '', 'Kipkorir'),
    ('Belgut', 169, u'Charles Keter', 'Charles', 'Cheruiyot', 'Keter'),
    ('Bobasi', 118, u'Mogere Obure', 'Christopher', 'Mogere', 'Obure'),
    ('Bomachoge', 127, u'Joel Onyancha', 'Joel', '', 'Onyancha'),
    ('Bomet', 176, u'Kipkalya Kones', 'Kipkalya', '', 'Kones'),
    ('Bonchari', 126, u'Charles Onyancha', 'Charles', '', 'Onyancha'),
    ('Bondo', 194, u'Oburu Odinga', 'Oburu', '', 'Odinga'),
    ('Budalangi', 108, u'Ababu Namwamba', 'Pius', 'Tawfiq Namwamba', 'Ababu'),
    ('Bumula', 208, u'Bifwoli Wakoli', 'Sylvester', 'Wakoli', 'Bifwoli'),
    ('Bura', 114, u'Nassir Nuh', 'Abdi', 'Nassir', 'Nuh'),
    ('Bureti', 157, u'Franklin Bett', 'Franklin', '', 'Bett'),
    ('Butere', 201, u'Wycliffe Oparanya', 'Wycliffe', '', 'Oparanya'),
    ('Butula', 119, u'Bwire Odhiambo', 'Bwire', 'Alfred', 'Odhiambo'),
    ('Central Imenti', 22, u'Gitobu Imanyara', 'Gitobu', '', 'Imanyara'),
    ('Changamwe', 163, u'Ramadhan Kajembe', 'Ramadhan', 'Seif', 'Kajembe'),
    ('Chepalungu', 136, u'Isaac Rutto', 'Isaac', '', 'Ruto'),
    ('Cherangany', 61, u'Joshua Kutuny', 'Joshua', '', 'Kutuny'),
    ('Dagoretti', 85, u'Beth Mugo', 'Beth', 'Wambui', 'Mugo'),
    ('Dujis', 15, u'Aden Dwale', 'Bare', 'Aden', 'Duale'),
    ('Eldama Ravine', 67, u'Moses Lessonet', 'Moses', '', 'Lessonet'),
    ('Eldoret East', 33, u'Margaret Kamar', 'Kamar', 'Margret', 'Jepkoech'),
    ('Eldoret North', 204, u'William Ruto', 'William', '', 'Ruto'),
    ('Eldoret South', 12, u'Chepchumba Peris', 'Peris', '', 'Chepchumba'),
    ('Embakasi', 147, u'Ferdinand Waititu', 'Ferdinand', "Ndung'u", 'Waititu'),
    ('Emgwen', 64, u'Elijah Lagat', 'Elijah', '', 'Lagat'),
    ('Emuhaya', 131, u'Wilbur Ottichilo', 'Wilbur', 'Ottichilo', ''),
    ('Fafi', 142, u'Aden Sugow', 'Ahmed', 'Aden', 'Sugow'),
    ('Funyula', 132, u'Nyongesa Otuoma', 'Otuoma', 'Paul', 'Nyogesa'),
    ('Gachoka', 95, u'Mutava Musyimi', 'Mutava', '', 'Musyimi'),
    ('Galole', 23, u'Gaddae Godhana', 'Dhadho', 'Gaddae', 'Goghana'),
    ('Ganze', 10, u'Francis Bayah', 'Francis', 'S. K.', 'Baya'),
    ('Garsen', 185, u'Danson Mungatana', 'Danson', 'Buya', 'Mungatana'),
    ('Gatanga', 167, u'Peter Kenneth', 'Peter', '', 'Kenneth'),
    ('Gatundu North', 146, u'Kungu Waibara', 'Clement', "Kung'u", 'Waibara'),
    ('Gatundu South', 168, u'Uhuru Kenyatta', 'Uhuru', 'Muigai', 'Kenyatta'),
    ('Gem', 184, u'Jakoyo Midiwo', 'Washington', 'Jakoyo', 'Midiwo'),
    ('Gichugu', 166, u'Martha Karua', 'Martha', 'Wangari', 'Karua'),
    ('Githunguri', 8, u'Peter Baiya', 'Peter', 'Njoroge', 'Baiya'),
    ('Gwassi', 110, u"Mbadi Ng'ongo", 'Mbadi', 'John', "Ng'ongo"),
    ('Hamisi', 171, u'George Khaniri', 'George', '', 'khaniri'),
    ('Igembe North', 72, u"Ntoitha M'Mithiaru", 'Ntoitha', '', "M'mithiaru"),
    ('Igembe South', 69, u'Mithika Linturi', 'Franklin', 'Mithika', 'Linturi'),
    ('Ijara', 26, u'Yusuf Haji', 'Mohamed', 'Yussuf', 'Haji'),
    ('Ikolomani', 170, u'Bonny Khalwale', 'Bonny', '', 'Khalwale'),
    ('Isiolo North', 60, u'Mohammed Kuti', 'Mohammed', 'Abdi', 'Kuti'),
    ('Isiolo South', 156, u'Abdul Bahari', 'Abdul', 'Bahari', 'Ali'),
    ('Juja', 144, u'George Thuo', 'George', '', 'Thuo'),
    ('Kacheliba', 202, u'Samuel Poghisio', 'Samuel', '', 'Poghisio'),
    ('Kaiti', 191, u'Gideon Ndambuki', 'Gideon', 'Musyoka', 'Ndambuki'),
    ('Kajiado Central', 192, u'Joseph Nkaissery', 'Joseph', 'Ole', 'Nkaissery'),
    ('Kajiado North', 205, u'Saitoti George ', 'George', '', 'Saitoti'),
    ('Kajiado South', 199, u'Katoo Ole Metito', 'Katoo', 'Ole', 'Metito'),
    ('Kaloleni', 39, u'Samuel Kazungu', 'Samwel', 'Kazungu', 'Kambi'),
    ('Kandara', 34, u'James Kamau', 'James', 'Maina', 'Kamau'),
    ('Kanduyi', 42, u"Khang'ati Alfred", 'Alfred', '', "Khang'ati"),
    ('Kangema', 183, u'John Michuki', 'John', 'Michuki', 'Njoroge'),
    ('Kangundo', 96, u'Johnson Muthama', 'Johnson', 'Nduya', 'Muthama'),
    ('Kapenguria', 90, u'Recha Murgor', 'Julius', '', 'Mugor'),
    ('Karachuonyo', 135, u'G Rege', 'James', 'Kwanya', 'Rege'),
    ('Kasarani', 125, u'Elizabeth Ongoro', 'Elizabeth', '', 'Ongoro'),
    ('Kasipul Kabondo', 73, u'Joseph Magwanga', 'Joseph', 'Oyugi', 'Magwanga'),
    ('Kathiani', 109, u'Wavinya Ndeti', 'Ndeti', '', 'Wavinya'),
    ('Keiyo North', 13, u'Lucas Chepkitony', 'Chepkitony', 'Lucas', 'Kipkosei'),
    ('Keiyo South', 52, u'Jackson Kiptanui', 'Kiptanui', 'Kiplagat', 'Jackson'),
    ('Khwisero', 4, u'Bulimo Akula', 'Evans', '', 'Akula'),
    ('Kiambaa', 21, u'Stanley Githunguri', 'Stanley', 'Munga', 'Githunguri'),
    ('Kibwezi', 62, u'Philip Kyalo', 'Philip', 'Kyalo', 'Kaloki'),
    ('Kieni', 150, u'Nemesyus Warugongo', 'Nemesius', '', 'Warugongo'),
    ('Kigumo', 35, u'Jamleck Kamau', 'Jamleck', 'Irungu', 'Kamau'),
    ('Kiharu', 102, u'Barnabas Mwangi', 'Barnabas', 'Muturi C.', 'Mwangi'),
    ('Kikuyu', 113, u'Lewis Nguyai', 'Lewis', 'Nguyai', 'Nganga'),
    ('Kilome', 105, u'John Mwau', 'John', 'Harun', 'Mwau'),
    ('Kimilili', 141, u'Eseli Simiyu', 'David', 'Eseli', 'Simiyu'),
    ('Kinango', 203, u'Samuel Rai', 'Samuel', 'Gonzi', 'Rai'),
    ('Kinangop', 112, u'Mwaniki Ngugi', 'David', 'Mwaniki', 'Ngugi'),
    ('Kipipiri', 174, u'Amos Kimunya', 'Amos', 'Muhinga', 'Kimunya'),
    ('Kipkelion', 51, u'Langat Kiprono', 'Kiprono', '', 'Langat'),
    ('Kirinyaga Central', 37, u'Ngata Kariuki', 'John', 'Ngata', 'Kariuki'),
    ('Kisauni', 30, u'Ali Joho', 'Hassan', 'Ali', 'Joho'),
    ('Kisumu Rural', 193, u"Anyang Nyong'o", 'Peter', "Anyang'", "Nyong'o"),
    ('Kisumu Town East', 140, u'Shekeel Shabir', 'Ahmed', 'Shakeel Shabbir', 'Ahmed'),
    ('Kisumu Town West', 5, u'Olago Aluoch', 'John', 'Olago', 'Aluoch'),
    ('Kitui Central', 111, u'Charity Ngilu', 'Charity', 'Kaluki', 'Ngilu'),
    ('Kitui South', 87, u'Isaac Muoki', 'Issac', 'Mulatya', 'Muoki'),
    ('Kitui West', 115, u'Mutisya Nyamai', 'Charles', 'Mutisya', 'Nyamai'),
    ('Kitutu Chache', 128, u'Momoima Onyonka', 'Richard', '', 'Momoima'),
    ('Kitutu Masaba', 116, u'Enock Nyambati', 'Walter', 'Enock Nyambati', 'Osebe'),
    ('Konoin', 53, u'Julius Kipyegon', 'Julius', 'Kipyegon', 'Kones'),
    ('Kuresoi', 14, u'Zakayo Cheuriyot', 'Zakayo', '', 'Cheroiyot'),
    ('Kuria', 179, u'Wilfred Machage', 'Wilfred', 'Gisuka', 'Machage'),
    ('Kwanza', 209, u'Noah Wekesa', 'Noah', '', 'Wakesa'),
    ('Lagdera', 16, u'Maalim Farah', 'Farah', '', 'Maalim'),
    ('Laikipia East', 175, u'Mwangi Kiunjuri', 'Kiunjuri', 'Festus', 'Mwangi'),
    ('Laikipia West', 91, u'Nderitu Muriithi', 'Muriithi', '', 'Nderitu'),
    ('Laisamis', 66, u'Joseph Lekuton', 'Joseph', 'Lemasolai', 'Lekuton'),
    ('Lamu East', 2, u'Mohamed Abu', 'Abu', 'Mohamed', 'Chiaba'),
    ('Lamu West', 145, u'Fahim Twaha', 'Yasin', 'Fahim', 'Twaha'),
    ('Langata', 195, u'Raila Odinga', 'Raila', 'Amolo', 'Odinga'),
    ('Lari', 106, u'David Mwaura', 'David', 'Njuguna Kiburi', 'Mwaura'),
    ('Likoni', 99, u'Mashud Mwahima', 'Mwalimu', 'Masudi', 'Mwahima'),
    ('Limuru', 104, u'Peter Mwathi', 'Peter', 'Mungai', 'Mwathi'),
    ('Lugari', 29, u'Cyrus Jirongo', 'Cyrus', '', 'Jirongo'),
    ('Lurambi', 40, u'Manyala Keya', 'Atanas', '', 'Keya'),
    ('Machakos Town', 86, u'Victor Munyaka', 'Victor', 'Kioko', 'Munyaka'),
    ('Magarini', 27, u'Amason Jeffah', 'Amason', 'Kingi', 'Jeffah'),
    ('Makadara', 152, u'Dickson Wathika', 'Dickson', 'Mwangi', 'Wathika'),
    ('Makueni', 45, u'Peter Kiilu', 'Peter', 'L. N.', 'Kiilu'),
    ('Malava', 207, u'Soita Shitanda', 'Soita', '', 'Shitanda'),
    ('Malindi', 76, u'Gideon Maitha', 'Maitha', 'Gideon', "Mung'aro"),
    ('Mandera Central', 1, u'Hussein Abdikadir', 'Hussein', 'Mohammed', 'Abdikadir'),
    ('Mandera East', 81, u'Hussein Mohamed', 'Mohamed', 'Hussein', 'Ali'),
    ('Manyatta', 38, u'Emilio Kathuri', 'Emillio', 'Mureithi', 'Kathuri'),
    ('Maragwa', 182, u'Elias Mbau', 'Peter', 'Elias', 'Mbau'),
    ('Marakwet East', 173, u'Linah Kilimo', 'Linah', '', 'Kilimo'),
    ('Marakwet West', 32, u'Kipchumba Kaino', 'Kaino', 'Boaz', 'Kipchuma'),
    ('Masinga', 181, u'Benson Mbai', 'Benson', 'Mbai', 'Itwiku'),
    ('Mathioya', 149, u'Clement Wambugu', 'Clement', 'Muchiri', 'Wambugu'),
    ('Mathira', 75, u'Ephraim Maina', 'Ephraim', 'Mwangi', 'Maina'),
    ('Matuga', 189, u'Ali Mwakwere', 'Ali', 'Chirau', 'Mwakwere'),
    ('Matungu', 153, u'Aoko Were', 'David', '', 'Were'),
    ('Mbita', 164, u"Otieno Kajwang'", 'Gerald', 'Otieno', 'Kajwang'),
    ('Mbooni', 47, u'Mutula Kilonzo', 'Mutula', '', 'Kilonzo'),
    ('Migori', 134, u'John Pesa', 'John', 'Pesa', 'Dache'),
    ('Mogotio', 28, u'Sambili Jepkemoi', 'Hellen', '', 'Sambili'),
    ('Molo', 54, u'Joseph Kiuna', 'Joseph', 'Nganga', 'Kiuna'),
    ('Mosop', 56, u'David Koech', 'David', '', 'Koech'),
    ('Moyale', 74, u'Ali Mahmoud', 'Mohamud', 'Mohammed', 'Ali'),
    ('Msambweni', 155, u'Omar Zonga', 'Omar', 'Mbwana', 'Zonga'),
    ('Mt Elgon', 36, u'Fred Kapondi', 'Fred', '', 'Kapondi'),
    ('Muhoroni', 122, u'Patrick Olweny', 'Patrick', 'Ayiecho', 'Olweny'),
    ('Mukurweini', 31, u'Wa Kabando', 'Kabando', 'wa', 'Kabando'),
    ('Mumias', 151, u'Jomo Washiali', 'Benjamin', 'Jomo', 'Washiali'),
    ('Mutito', 172, u'Kilonzo Kiema', 'Julius', 'Kiema', 'Kilonzo'),
    ('Mvita', 9, u'Najib Balala', 'Najib', 'Mohamed', 'Balala'),
    ('Mwala', 88, u'Mutua Muoki', 'Daniel', 'Mutua', 'Muoki'),
    ('Mwatate', 103, u'Calyst Mwatela', 'Calist', 'Andrew', 'Mwatela'),
    ('Mwea', 20, u'Peter Gitau', 'Peter', 'Njuguna', 'Gitau'),
    ('Mwingi North', 188, u'Kalonzo Musyoka', 'Stephen', 'Kalonzo', 'Musyoka'),
    ('Mwingi South', 94, u'David Musila', 'David', '', 'Musila'),
    ('Naivasha', 97, u'John Mututho', 'John', 'Michael Njenga', 'Mututho'),
    ('Nakuru Town', 48, u'Lee Kinyanjui', 'Lee', 'Maiyani', 'Kinyanjui'),
    ('Nambale', 198, u'Chrysanthus Okemo', 'Chrysanthus', '', 'Okemo'),
    ('Narok North', 200, u'William Ole Ntimama', 'William', 'Ronkorua', 'Ntimama'),
    ('Narok South', 65, u'Nkoidila Lankas', 'Nkoidilla', '', 'Lankas'),
    ('Ndaragwa', 49, u'Jeremiah Kioni', 'Jeremiah', 'Ngayu', 'Kioni'),
    ('Ndhiwa', 197, u'Joshua Ojodeh', 'Joshua', 'Orwa', 'Ojodeh'),
    ('Ndia', 159, u'Njeru Githae', 'Robinson', 'Njeru', 'Githae'),
    ('Nithi', 79, u'Japeth Mbiuki', 'Japhet', 'M. Kareke', 'Mbiuki'),
    ('North Horr', 18, u'Chachu Ganya', 'Francis', 'Chachu', 'Ganya'),
    ('North Imenti', 92, u'Silas Muriuki', 'Silas', 'Muriuki', 'Ruteere'),
    ('North Mugirango Borabu', 123, u'Moriasi Ombui', 'Moriasi', 'Wilfred', 'Ombui'),
    ('Nyakach', 7, u'Pollyins Anyango', 'Pollyins', 'Ochieng', 'Anyango'),
    ('Nyando', 133, u'Frederick Outa', 'Frederick', 'Outa', 'Otieno'),
    ('Nyaribari Chache', 83, u'Robert Monda', 'Robert', 'Onsare', 'Monda'),
    ('Nyaribari Masaba', 124, u'Kagengo Ongeri', 'Samson', 'Kagengo', 'Ongeri'),
    ('Nyatike', 6, u'Omondi Anyanga', 'Peter', 'Edick Omondi', 'Anyanga'),
    ('Nyeri Town', 77, u'Murugi Mathenge', 'Esther', 'Murugi', 'Mathenge'),
    ('Ol Kalou', 89, u'Erastus Mureithi', 'Erastus', 'Kihara', 'Mureithi'),
    ('Othaya', 43, u'Mwai Kibaki', 'Mwai', 'Emilio', 'Kibaki'),
    ('Rangwe', 120, u'Martin Ogindo', 'Martin', 'Otieno', 'Ogindo'),
    ('Rarieda', 24, u'Nicholas Gumbo', 'Nicholas', '', 'Gumbo'),
    ('Rongai', 44, u'Luka Kigen', 'Kigen', 'Luka', 'Kipkorir'),
    ('Rongo', 130, u'Dalmas Otieno', 'Dalmas', 'Anyango', 'Otieno'),
    ('Runyenjes', 78, u'Cecily Mbarire', 'Cecily', 'Mutitu', 'Mbarire'),
    ('Sabatia', 84, u'Musailia Mudavadi', 'Musalia', '', 'Mudavadi'),
    ('Saboti', 148, u'Eugene Wamalwa', 'Eugene', 'Ludovic', 'Wamalwa'),
    ('Saku', 138, u'Hussein Sasura', 'Hussein', 'Tarry', 'Sasura'),
    ('Samburu East', 68, u'Raphael Letimalo', 'Raphael', '', 'Lentimalo'),
    ('Samburu West', 178, u'Simon Lesirma', 'Simon', '', 'Lesirma'),
    ('Shinyalu', 71, u'Charles Lugano', 'Justus', 'Kizito', 'Mugali'),
    ('Siakago', 55, u'Lenny Kivuti', 'Lenny', 'Maxwell', 'Kivuti'),
    ('Sigor', 70, u'Wilson Litole', 'Wilson', '', 'Litole'),
    ('Sirisia', 210, u'Moses Wetangula', 'Moses', '', 'Wetangula'),
    ('Sotik', 211, u'Lorna Laboso', 'Lorna', '', 'Laboso'),
    ('South Imenti', 93, u'Kiraitu Murungi', 'Kiraitu', '', 'Murungi'),
    ('South Mugirango', 180, u'Omingo Magara', 'James', 'Omingo', 'Magara'),
    ('Subukia', 17, u'Nelson Gaichuhie', 'Nelson', '', 'Gaichuhie'),
    ('Taveta', 139, u'Naomi Shaban', 'Naomi', 'Namisi', 'Shaban'),
    ('Tetu', 117, u'Francis Nyammo', 'Francis', 'Thombe', 'Nyammo'),
    ('Tharaka', 107, u'Alex Mwiru', 'Alex', 'Muthengi Mburi', 'Mwiru'),
    ('Tigania East', 186, u'Peter Munya', 'Peter', 'Gatirau', 'Munya'),
    ('Tigania West', 190, u'Kilemi Mwiria', 'Valerian', 'Kalemi', 'Mwiria'),
    ('Tinderet', 177, u'Henry Kosgey', 'Henry', 'Kiprono', 'Kosgey'),
    ('Turkana Central', 158, u'David Ethuro', 'David', '', 'Ethuro'),
    ('Turkana North', 187, u'John Munyes', 'John', '', 'Munyes'),
    ('Turkana South', 57, u'Nanok Koli', 'Josephat', 'Koli', 'Nanok'),
    ('Ugenya', 129, u'James Orengo', 'James', '', 'Orengo'),
    ('Uriri', 121, u'Cyprian Ojwang', 'Cyprian', 'Ojwang', 'Omollo'),
    ('Vihiga', 11, u'Kifuma Chanzu', 'Yusuf', 'Kifuma', 'Chanzu'),
    ('Voi', 101, u'Danson Mwakulegwa', 'Danson', 'Mwazo', 'Mwakulegwa'),
    ('Wajir East', 82, u'Elmi Mohammed', 'Ibrahim', 'Elmi', 'Mohamed'),
    ('Wajir South', 161, u'Ali Hassan', 'Abdirahman', 'Ali', 'Hassan'),
    ('Wajir West', 41, u'Adnan Keynan', 'Adan', 'Keynan', 'Wehliye'),
    ('Webuye', 137, u'Alfred Sambu', 'Alfred', '', 'Sambu'),
    ('West Mugirango', 19, u'Ondicho Gesami', 'James', 'Ondicho', 'Gesami'),
    ('Westlands', 160, u'Frederick Gumo', 'Fred', 'Omulo', 'Gumo'),
    ('Wundanyi', 98, u'Thomas Mwadeghu', 'Thomas', 'Luhindi', 'Mwadeghu'),
    ('Yatta', 46, u'Charles Kilonzo', 'Charles', 'Mutavi', 'Kilonzo'),
]

for rename in renames:
    (constituency, id, name, first, middle, last) = rename
    person = models.Person.objects.get(id=id)
    person.first_name   = first
    person.middle_names = middle
    person.last_name    = last
    person.save()



for obj in models.Place.objects.all():
    slug = slugify( obj.name )
    if slug != obj.slug:
        print "changing place slug from '%s' to '%s'" % (obj.slug, slug)
        obj.slug = slug
        obj.save()


for obj in models.Person.objects.all():
    slug = slugify( obj.name )
    if slug != obj.slug:
        print "changing person slug from '%s' to '%s'" % (obj.slug, slug)
        obj.slug = slug
        obj.save()


