# This was generated from ./manage.py kenya_import_electoral_offices

IEBC_OFFICE_DATA = [{'address': 'DC\xe2\x80\x99S COMPOUND NGONG',
  'cons_id': 5240,
  'cons_name': u'KAJIADO NORTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0720756536'},
 {'address': 'DC\xe2\x80\x99S COMPOUND KAJIADO',
  'cons_id': 5236,
  'cons_name': u'KAJIADO CENTRAL',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0723698430'},
 {'address': 'AIC KISERIAN',
  'cons_id': 5237,
  'cons_name': u'KAJIADO WEST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722355773'},
 {'address': 'MASAI RURAL CENTRE ISINYA',
  'cons_id': 5238,
  'cons_name': u'KAJIADO EAST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0720015755'},
 {'address': 'DDOS COMPOUND LOITOKTOK',
  'cons_id': 5239,
  'cons_name': u'KAJIADO SOUTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0720804285'},
 {'address': 'DC\xe2\x80\x99S COMPOUND WESTLANDS',
  'cons_id': 5069,
  'cons_name': u'WESTLANDS',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0722798861'},
 {'address': 'MALIPOSA BUILDING NGONG ROAD',
  'cons_id': 5070,
  'cons_name': u'DAGORETTI NORTH',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0716455241'},
 {'address': 'DC\xe2\x80\x99S COMPOUND KAWANGWARE',
  'cons_id': 5074,
  'cons_name': u'DAGORETTI SOUTH',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0733326084'},
 {'address': 'WILSON AIRPORT CHIEF\xe2\x80\x99S COMPOUND',
  'cons_id': 5073,
  'cons_name': u'LANGATA',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0718248027'},
 {'address': 'DC\xe2\x80\x99S OFFICE KIBRA',
  'cons_id': 5077,
  'cons_name': u'KIBRA',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0722653748'},
 {'address': "DC'S OFFICE KASARANI",
  'cons_id': 5075,
  'cons_name': u'KASARANI',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0722508828'},
 {'address': "DC'S OFFICE KASARANI",
  'cons_id': 5071,
  'cons_name': u'ROYSAMBU',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0724802423'},
 {'address': 'SACRED HEART CHURCH BABADOGO',
  'cons_id': 5076,
  'cons_name': u'RUARAKA',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0712866251'},
 {'address': 'DONHOLM ROUNDABOUT',
  'cons_id': 5338,
  'cons_name': u'EMBAKASI WEST',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0725126173'},
 {'address': 'CHIEF\xe2\x80\x99S COMPOUND, VILLAGE , EMBAKASI',
  'cons_id': 5339,
  'cons_name': u'EMBAKASI EAST',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0722752050'},
 {'address': 'DO\xe2\x80\x99S COMPOUND KAYOLE',
  'cons_id': 5341,
  'cons_name': u'EMBAKASI CENTRAL',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0725492790'},
 {'address': 'DO\xe2\x80\x99S COMPOUND DANDORA',
  'cons_id': 5340,
  'cons_name': u'EMBAKASI NORTH',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0721313181'},
 {'address': 'VILLA FRANCA, JVILLA SUPERMARKET BUILDING',
  'cons_id': 5342,
  'cons_name': u'EMBAKASI SOUTH',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0721686407'},
 {'address': 'DC\xe2\x80\x99S COMPOUND PUMWANI',
  'cons_id': 5068,
  'cons_name': u'KAMUKUNJI',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0720935328'},
 {'address': 'MINISTRY OF PUBLIC WORKS COMPOUND, INDUSTRIAL AREA.',
  'cons_id': 5343,
  'cons_name': u'MAKADARA',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0722841900'},
 {'address': 'KIE OFFICES NGARA',
  'cons_id': 5072,
  'cons_name': u'STAREHE',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0722276410'},
 {'address': 'KIE OFFICES NGARA',
  'cons_id': 5078,
  'cons_name': u'MATHARE',
  'missing': False,
  'prov_id': 5,
  'prov_name': u'Nairobi',
  'telephone': '0733543618'},
 {'address': 'RONGO DISTRICT HQ',
  'cons_id': 5303,
  'cons_name': u'RONGO',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 466 302'},
 {'address': 'AWENDO DISTRICT HQ',
  'cons_id': 5300,
  'cons_name': u'AWENDO',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0721 566 430'},
 {'address': 'MIGORI DISTRICT HQ',
  'cons_id': 5349,
  'cons_name': u'SUNA EAST',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 293 609'},
 {'address': 'BONDO NYIRONGE/NCPB Depot',
  'cons_id': 5350,
  'cons_name': u'SUNA WEST',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 578 292'},
 {'address': 'GRACE OUTREACH-URIRI',
  'cons_id': 5302,
  'cons_name': u'URIRI',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0728 459 438'},
 {'address': 'MACALDER',
  'cons_id': 5299,
  'cons_name': u'NYATIKE',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0727 902 716'},
 {'address': 'KEHANCHA',
  'cons_id': 5301,
  'cons_name': u'KURIA WEST',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0720 565 657'},
 {'address': 'KEGONGA.',
  'cons_id': 5298,
  'cons_name': u'KURIA EAST',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 793 623'},
 {'address': 'SUNEKA',
  'cons_id': 5310,
  'cons_name': u'BONCHARI',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0733 964 945'},
 {'address': 'NYAMARAMBE TOWNSHIP',
  'cons_id': 5312,
  'cons_name': u'SOUTH MUGIRANGO',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 564 796'},
 {'address': 'MAGENA TOWNSHIP',
  'cons_id': 5309,
  'cons_name': u'BOMACHOGE BORABU',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0711 423 750'},
 {'address': "SAMETA DC's OFFICE",
  'cons_id': 5308,
  'cons_name': u'BOBASI',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 251 913'},
 {'address': 'OGEMBO TOWNSHIP',
  'cons_id': 5307,
  'cons_name': u'BOMACHOGE CHACHE',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0726 425 551'},
 {'address': 'MASIMBA',
  'cons_id': 5306,
  'cons_name': u'NYARIBARI MASABA',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0727 281 623'},
 {'address': 'KEUMBU',
  'cons_id': 5304,
  'cons_name': u'NYARIBARI CHACHE',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 153 729'},
 {'address': 'MARANI',
  'cons_id': 5305,
  'cons_name': u'KITUTU CHACHE NORTH',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0721 293 662'},
 {'address': 'KISII TOWN',
  'cons_id': 5311,
  'cons_name': u'KITUTU CHACHE SOUTH',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0721 576 104'},
 {'address': 'MANGA DISTRICT HQs',
  'cons_id': 5320,
  'cons_name': u'KITUTU MASABA',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0721 592 152'},
 {'address': 'NYAMIRA TOWN',
  'cons_id': 5319,
  'cons_name': u'WEST MUGIRANGO',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0723 837 010'},
 {'address': 'EKERENYO',
  'cons_id': 5318,
  'cons_name': u'NORTH MUGIRANGO',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0714 400 675'},
 {'address': 'NYANSIONGO',
  'cons_id': 5321,
  'cons_name': u'BORABU',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0721 384 596'},
 {'address': 'MINISTRY OF NATIONAL PLANNING BUILDING \xe2\x80\x93 UKWALA TOWN',
  'cons_id': 5284,
  'cons_name': u'UGENYA',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0721 544 767'},
 {'address': 'OPP. UGUNJA DC\xe2\x80\x99s OFFICE \xe2\x80\x93 UGUNJA TOWN',
  'cons_id': 5287,
  'cons_name': u'UGUNJA',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0721 752 410'},
 {'address': 'DC\xe2\x80\x99s COMPOUND \xe2\x80\x93 SIAYA TOWN',
  'cons_id': 5289,
  'cons_name': u'ALEGO USONGA',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0721 336 801'},
 {'address': 'OPPOSITE GEM CDF OFFICE ALONG LUANDA SIAYA ROAD',
  'cons_id': 5288,
  'cons_name': u'GEM',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0714 148 910'},
 {'address': 'BONDO - SIAYA JUNCTION',
  'cons_id': 5286,
  'cons_name': u'BONDO',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 289377'},
 {'address': 'KALANDINI TOWN',
  'cons_id': 5285,
  'cons_name': u'RARIEDA',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0721 419 231'},
 {'address': 'NEXT TO KISUMU EAST DC\xe2\x80\x99s OFFICE \xe2\x80\x93 OPP. KISUMU COUNTY ASSEMBLY CHAMBERS',
  'cons_id': 5326,
  'cons_name': u'KISUMU EAST',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0729 934 824'},
 {'address': 'MASENO BEHIND LAW COURTS',
  'cons_id': 5325,
  'cons_name': u'KISUMU WEST',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0734 483 722'},
 {'address': 'AT THE New NYANZA PROVINCIAL HQS Building next to Central Bank Kisumu',
  'cons_id': 5328,
  'cons_name': u'KISUMU CENTRAL',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 691 811'},
 {'address': 'KOMBEWA TOWN NEXT TO THE DO\xe2\x80\x99s OFFICE',
  'cons_id': 5323,
  'cons_name': u'SEME',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 426 682'},
 {'address': 'MIN. OF GENDER, CHILDREN & SOCIAL SERVICES\xe2\x80\x99 compound',
  'cons_id': 5324,
  'cons_name': u'NYANDO',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0720 321 420'},
 {'address': 'WITHIN SUGARBELT OFFICES',
  'cons_id': 5327,
  'cons_name': u'MUHORONI',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 691 871'},
 {'address': 'PAP ONDITI TOWN',
  'cons_id': 5322,
  'cons_name': u'NYAKACH',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0721 213 517'},
 {'address': 'LOCATED WITHIN RACHUONYO SOUTH DC\xe2\x80\x99s OFFICE KOSELE',
  'cons_id': 5291,
  'cons_name': u'KASIPUL',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0721 590 567'},
 {'address': 'KADONGO CENTRE',
  'cons_id': 5294,
  'cons_name': u'KABONDO KASIPUL',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0720 285 908'},
 {'address': 'RACHUONYO DISTRICT HEADQURTERS ROOM 16',
  'cons_id': 5293,
  'cons_name': u'KARACHUONYO',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 790 881'},
 {'address': 'CDF BUILDING OR AP LINESRANGWE CENTRE',
  'cons_id': 5290,
  'cons_name': u'RANGWE',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 856 270'},
 {'address': 'DC\xe2\x80\x99s COMPOUND \xe2\x80\x93 HOMABAY TOWN',
  'cons_id': 5297,
  'cons_name': u'HOMA BAY TOWN',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0723 267 679'},
 {'address': 'LOCATED WITHIN THE DC\xe2\x80\x99s COMPOUND NDHIWA TOWN',
  'cons_id': 5296,
  'cons_name': u'NDHIWA',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0710 335 478'},
 {'address': 'LOCATED WITHIN THE DC\xe2\x80\x99s PREMISES',
  'cons_id': 5295,
  'cons_name': u'MBITA',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0725 296 561'},
 {'address': 'WITHIN MAGUNGA CENTRE',
  'cons_id': 5292,
  'cons_name': u'SUBA',
  'missing': False,
  'prov_id': 7,
  'prov_name': u'Nyanza',
  'telephone': '0722 455 080'},
 {'address': 'COUNTY COUNCIL OF TRANSMARA- KILGORIS',
  'cons_id': 5232,
  'cons_name': u'KILGORIS',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'DISTRICT COMMISSIONERS OFFICE - EMURUA DIKIRR',
  'cons_id': 5234,
  'cons_name': u'EMURUA DIKIRR',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'DISTRICT COMMISSIONERS OFFICE- NAROK',
  'cons_id': 5231,
  'cons_name': u'NAROK NORTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'NTULELE CENTRE - OPPOSITE POLICE STATION',
  'cons_id': 5235,
  'cons_name': u'NAROK EAST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'OLOLULUNGA CENTRE - NEXT TO DISTRICT HOSPITAL',
  'cons_id': 5230,
  'cons_name': u'NAROK SOUTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'NKORKORRI BOYS SEC. SCHOOL',
  'cons_id': 5233,
  'cons_name': u'NAROK WEST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'POSTAL CORPORATION OF KENYA - KIPKELION',
  'cons_id': 5250,
  'cons_name': u'KIPKELION EAST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'POSTAL CORPORATION OF KENYA - LONDIANI',
  'cons_id': 5248,
  'cons_name': u'KIPKELION WEST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'DISTRICT COMMISIONERS OFFICE - KERICHO',
  'cons_id': 5251,
  'cons_name': u'AINAMOI',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'BURETI GROWERS SACCO LTD - LITEIN',
  'cons_id': 5313,
  'cons_name': u'BURETI',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': "SOSIOT CENTRE - OPPOSITE DC'S OFFICE",
  'cons_id': 5247,
  'cons_name': u'BELGUT',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'SOKO HURU SHOPPING CENTRE ALONG KERICHO AWASI',
  'cons_id': 5249,
  'cons_name': u'SIGOWET/SOIN',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'POSTAL CORPORATION OF KENYA - SOTIK',
  'cons_id': 5316,
  'cons_name': u'SOTIK',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'COUNTY COUNCIL OF BOMET - BOMET',
  'cons_id': 5314,
  'cons_name': u'CHEPALUNGU',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'COUNTY COUNCIL OF BOMET - BOMET',
  'cons_id': 5315,
  'cons_name': u'BOMET EAST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'NATIONAL CEREALS AND PRODUCE BOARD - BOMET',
  'cons_id': 5317,
  'cons_name': u'BOMET CENTRAL',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'MOGOGOSIEK SHOPPING CENTRE',
  'cons_id': 5252,
  'cons_name': u'KONOIN',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': 'DO\xe2\x80\x99s compound\xe2\x80\x93Kiamaina/Maili Sita, Bahati',
  'cons_id': 5229,
  'cons_name': u'BAHATI',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0724 585 675'},
 {'address': 'County Commissioner\xe2\x80\x99s premises, opposite Posta Building \xe2\x80\x93 Kabarnet Town.',
  'cons_id': 5212,
  'cons_name': u'BARINGO CENTRAL',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0724 344 058'},
 {'address': 'Behind Posta Building \xe2\x80\x93 Baringo North',
  'cons_id': 5213,
  'cons_name': u'BARINGO NORTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0733 699 780'},
 {'address': 'District HQ Marigat District - Kabarnet.',
  'cons_id': 5216,
  'cons_name': u'BARINGO SOUTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722 255 700'},
 {'address': 'District Commissioner\xe2\x80\x99s Compound \xe2\x80\x93 Eldama Ravine',
  'cons_id': 5215,
  'cons_name': u'ELDAMA RAVINE',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0723 346 646'},
 {'address': 'Hennsolex Building, Ground floor \xe2\x80\x93 Gilgil Town.',
  'cons_id': 5225,
  'cons_name': u'GILGIL',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722 603 846'},
 {'address': 'Sachora, Sirikwa Police Post Building \xe2\x80\x93 Kuresoi.',
  'cons_id': 5227,
  'cons_name': u'KURESOI NORTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722 970 659'},
 {'address': 'Keringet Center',
  'cons_id': 5220,
  'cons_name': u'KURESOI SOUTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0718 892 561'},
 {'address': 'DC\xe2\x80\x99s Compound - Nanyuki Town',
  'cons_id': 5352,
  'cons_name': u'LAIKIPIA EAST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0721 295 074'},
 {'address': 'County council office, Dol Dol \xe2\x80\x93 Laikipia North',
  'cons_id': 5218,
  'cons_name': u'LAIKIPIA NORTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0721 518 171'},
 {'address': 'Telcom building, Nyahururu Law Court \xe2\x80\x93 Nyahururu Town.',
  'cons_id': 5351,
  'cons_name': u'LAIKIPIA WEST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0716 774 555'},
 {'address': 'Behind Boresha Sacco - Mogotio Township',
  'cons_id': 5214,
  'cons_name': u'MOGOTIO',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722 426 527'},
 {'address': 'DC\xe2\x80\x99s Compound - Molo Town',
  'cons_id': 5228,
  'cons_name': u'MOLO',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722 452 071'},
 {'address': 'DC\xe2\x80\x99s Road Opposite ACK Church \xe2\x80\x93 Naivasha.',
  'cons_id': 5224,
  'cons_name': u'NAIVASHA',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0716 454 014'},
 {'address': 'Catholic Diocese of Nakuru (CDN) Compound - Nakuru',
  'cons_id': 5222,
  'cons_name': u'NAKURU TOWN EAST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722 453 222'},
 {'address': 'District Public Works opposite KFA \xe2\x80\x93Nakuru',
  'cons_id': 5226,
  'cons_name': u'NAKURU TOWN WEST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0717 562 276'},
 {'address': 'AIC Church Compound - Njoro.',
  'cons_id': 5221,
  'cons_name': u'NJORO',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0723 633 631'},
 {'address': 'Farming System in Kiamunyi \xe2\x80\x93 Nakuru.',
  'cons_id': 5223,
  'cons_name': u'RONGAI',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0729 348 796'},
 {'address': 'Wamba Catholic Mission - Samburu',
  'cons_id': 5198,
  'cons_name': u'SAMBURU EAST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0721 681 383'},
 {'address': 'Near DC\xe2\x80\x99s Office- Baragoi',
  'cons_id': 5196,
  'cons_name': u'SAMBURU NORTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722 366 718'},
 {'address': 'Next to CDF office and Opposite DC\xe2\x80\x99s office \xe2\x80\x93 Samburu',
  'cons_id': 5197,
  'cons_name': u'SAMBURU WEST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0711 320 345'},
 {'address': 'Mwanainchi Sacco Building - Subukia Town Center.',
  'cons_id': 5219,
  'cons_name': u'SUBUKIA',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0720 409 802'},
 {'address': 'Chemolingot \xe2\x80\x93next to Ministry of education.',
  'cons_id': 5217,
  'cons_name': u'TIATY',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0721 245 563'},
 {'address': 'DC OFFFICE ELD-WEST',
  'cons_id': 5201,
  'cons_name': u'SOY',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0735 96 55 43'},
 {'address': 'West Indies BEHIND NATIONAL OIL /VC CHURCH',
  'cons_id': 5202,
  'cons_name': u'TURBO',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0729 029727'},
 {'address': 'West Indies BEHIND NATIONAL OIL /VC CHURCH',
  'cons_id': 5200,
  'cons_name': u'MOIBEN',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722 589432'},
 {'address': 'DC OFFFICE ELD-WEST',
  'cons_id': 5199,
  'cons_name': u'AINABKOI',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0712 276096'},
 {'address': 'JAMBONI COMPLEX',
  'cons_id': 5203,
  'cons_name': u'KESSES',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0704 656307'},
 {'address': 'RCEA INTERVENTION CENTRE',
  'cons_id': 5204,
  'cons_name': u'KAPSERET',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0713 485 587'},
 {'address': 'POKOT GOVERNORS OFFICE',
  'cons_id': 5192,
  'cons_name': u'SIGOR',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0721218650'},
 {'address': 'CHEPARERIA',
  'cons_id': 5194,
  'cons_name': u'POKOT SOUTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0724 050784'},
 {'address': 'KAPENGURIA COUNTY COUNCIL',
  'cons_id': 5191,
  'cons_name': u'KAPENGURIA',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0727076247'},
 {'address': 'POKOT GOVERNORS OFFICE',
  'cons_id': 5193,
  'cons_name': u'KACHELIBA',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0723141544'},
 {'address': 'Lodwar DC Office',
  'cons_id': 5185,
  'cons_name': u'TURKANA NORTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722 866483'},
 {'address': 'Kakuma DC OFFICE',
  'cons_id': 5188,
  'cons_name': u'TURKANA WEST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0723808770'},
 {'address': 'DC office Turkana central',
  'cons_id': 5187,
  'cons_name': u'TURKANA CENTRAL',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722 983740'},
 {'address': 'Lorugum DC office',
  'cons_id': 5189,
  'cons_name': u'LOIMA',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0723 337971'},
 {'address': 'Lokichar DC office',
  'cons_id': 5190,
  'cons_name': u'TURKANA SOUTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722939951'},
 {'address': 'LOKIRI DC DISTRICT HQ',
  'cons_id': 5186,
  'cons_name': u'TURKANA EAST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0720 438088'},
 {'address': 'ITEN TOWN-IEBC BUILDING',
  'cons_id': 5206,
  'cons_name': u'KEIYO NORTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722 457287'},
 {'address': 'KEIYO TEACHERS SACCO BLD-KIPKWEN RD CHEPKORIO',
  'cons_id': 5207,
  'cons_name': u'KEIYO SOUTH',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722 789002'},
 {'address': 'KAPSOWAR CENTRE',
  'cons_id': 5195,
  'cons_name': u'MARAKWET WEST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0720 172608'},
 {'address': 'KAPSOWAR CENTRE',
  'cons_id': 5205,
  'cons_name': u'MARAKWET EAST',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0722 495839'},
 {'address': 'Reformed Church of East Africa, Ushirika Intervention Centre \xe2\x80\x93 Opposite Hill School',
  'cons_id': 5204,
  'cons_name': u'KAPSERET',
  'missing': False,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': '0713485587'},
 {'address': 'Kisiero Building, Kapsokwony Market',
  'cons_id': 5269,
  'cons_name': u'MT. ELGON',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0721217569'},
 {'address': 'Kimilili Mkt next',
  'cons_id': 5270,
  'cons_name': u'KIMILILI',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0721706723'},
 {'address': 'At NCPB Premises',
  'cons_id': 5268,
  'cons_name': u'KANDUYI',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0729812994'},
 {'address': 'Next to DC\xe2\x80\x99s Office',
  'cons_id': 5272,
  'cons_name': u'BUMULA',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0725782682'},
 {'address': 'Former Municipal Council Offices within DC\xe2\x80\x99s Compound',
  'cons_id': 5271,
  'cons_name': u'SIRISIA',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0724245990'},
 {'address': 'At Chwele Mkt, Along Sirisia Rd, Alpha House, 3rdFloor',
  'cons_id': 5275,
  'cons_name': u'KABUCHAI',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0721519043'},
 {'address': 'After T Junction, Off Webuye, Kitale Road',
  'cons_id': 5274,
  'cons_name': u'WEBUYE EAST',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0711517134'},
 {'address': 'Bokoli Market',
  'cons_id': 5276,
  'cons_name': u'WEBUYE WEST',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0720762835'},
 {'address': 'Tongaren Market, Next to DO\xe2\x80\x99s office',
  'cons_id': 5273,
  'cons_name': u'TONGAREN',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0726427176'},
 {'address': 'Amagoro, Along Malaba Rd, next to Bungoma stage',
  'cons_id': 5277,
  'cons_name': u'TESO NORTH',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0722501345'},
 {'address': 'At DC\xe2\x80\x99s Compound, Amukura',
  'cons_id': 5280,
  'cons_name': u'TESO SOUTH',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0721605704'},
 {'address': 'Busia DC\xe2\x80\x99s Compound, IEBC Matayos, 1stFloor',
  'cons_id': 5282,
  'cons_name': u'NAMBALE',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0721272725'},
 {'address': 'Busia District Commissioner\xe2\x80\x99s Compound',
  'cons_id': 5281,
  'cons_name': u'MATAYOS',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0722242192'},
 {'address': 'Next to Constituency Development Fund (CDF) Butula',
  'cons_id': 5278,
  'cons_name': u'BUTULA',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0725959219'},
 {'address': 'Funyula Mkt, 100M from DC\xe2\x80\x99s Office',
  'cons_id': 5279,
  'cons_name': u'FUNYULA',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0721646447'},
 {'address': 'Port Victoria, near AP Line',
  'cons_id': 5283,
  'cons_name': u'BUDALANGI',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0728575856'},
 {'address': 'LUANDA - EMUHAYA RD',
  'cons_id': 5265,
  'cons_name': u'LUANDA',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0720951500'},
 {'address': 'NAVAKHOLO DISTRICT HQ',
  'cons_id': 5261,
  'cons_name': u'NAVAKHOLO',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0723502628'},
 {'address': 'LIKUYANI DISTRICT HQ',
  'cons_id': 5335,
  'cons_name': u'LIKUYANI',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '072630950'},
 {'address': 'SHIANDA MARKET -MUMIAS KAKAMEGA RD',
  'cons_id': 5262,
  'cons_name': u'MUMIAS EAST',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0720616723'},
 {'address': 'Friends Church near Malava Boys High School',
  'cons_id': 5257,
  'cons_name': u'MALAVA',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0722373531'},
 {'address': 'Lumakanda Town',
  'cons_id': 5329,
  'cons_name': u'LUGARI',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0721616210'},
 {'address': 'Bomani Mumias',
  'cons_id': 5260,
  'cons_name': u'MUMIAS WEST',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0722495894'},
 {'address': 'Saka Building along Kholera Road, Matungu Market',
  'cons_id': 5254,
  'cons_name': u'MATUNGU',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0729 778609'},
 {'address': 'National Cereals & Produce Board Kakamega',
  'cons_id': 5259,
  'cons_name': u'LURAMBI',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0722 437294'},
 {'address': 'Lirhanda Friends Church along Kakamega-Shinyalu Road',
  'cons_id': 5253,
  'cons_name': u'SHINYALU',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0723 169091'},
 {'address': 'Makhokho shopping Centre (Kakamega-Kisumu Road)',
  'cons_id': 5258,
  'cons_name': u'IKOLOMANI',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0725 891710'},
 {'address': 'Tsalwa Plaza Building opposite Butere Police Station',
  'cons_id': 5255,
  'cons_name': u'BUTERE',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0710895646'},
 {'address': 'Khwisero Town Centre',
  'cons_id': 5256,
  'cons_name': u'KHWISERO',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0727 769498'},
 {'address': 'Ebusiralo, along Ebusakami-Kima Road',
  'cons_id': 5267,
  'cons_name': u'EMUHAYA',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0722626862'},
 {'address': 'National Cereals & Produce Board Chavakali',
  'cons_id': 5264,
  'cons_name': u'SABATIA',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0734978130'},
 {'address': 'Mbale Municipal Council Office',
  'cons_id': 5266,
  'cons_name': u'VIHIGA',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0718036034'},
 {'address': 'HAMISI DISTRICT HQ',
  'cons_id': 5263,
  'cons_name': u'HAMISI',
  'missing': False,
  'prov_id': 9,
  'prov_name': u'Western',
  'telephone': '0722499800'},
 {'address': 'LIKONI SCHOOL FOR THE BLIND, PELELEZA',
  'cons_id': 5353,
  'cons_name': u'CHANGAMWE',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': '0202539391'},
 {'address': 'NEXT TO DOS OFFICE',
  'cons_id': 5081,
  'cons_name': u'JOMVU',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': '0721353656'},
 {'address': '',
  'cons_id': 5079,
  'cons_name': u'KISAUNI',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5082,
  'cons_name': u'NYALI',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5083,
  'cons_name': u'LIKONI',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5080,
  'cons_name': u'MVITA',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5087,
  'cons_name': u'MSAMBWENI',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5086,
  'cons_name': u'LUNGA LUNGA',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5085,
  'cons_name': u'MATUGA',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5084,
  'cons_name': u'KINANGO',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5084,
  'cons_name': u'KINANGO',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5103,
  'cons_name': u'TAVETA',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5103,
  'cons_name': u'TAVETA',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5100,
  'cons_name': u'WUNDANYI',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5102,
  'cons_name': u'MWATATE',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5101,
  'cons_name': u'VOI',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5101,
  'cons_name': u'VOI',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': 'Kilifi Town,Next To The District Commissioners Office',
  'cons_id': 5090,
  'cons_name': u'KILIFI NORTH',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': '0721202761'},
 {'address': 'OPPOSITE NATIONAL BANK MTWAPA',
  'cons_id': 5091,
  'cons_name': u'KILIFI SOUTH',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': '0720812025'},
 {'address': 'LOCATED IN KALOLENI TOWN IN BUILDING FORMERLY OCCUPIED BY WORLD VISION',
  'cons_id': 5088,
  'cons_name': u'KALOLENI',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': '0720494548'},
 {'address': 'mwawesa, Rabai district HQ OFF MAZERA KALOLENI ROAD',
  'cons_id': 5093,
  'cons_name': u'RABAI',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': '0721401671'},
 {'address': 'Ganze District Headquaters Office Block',
  'cons_id': 5089,
  'cons_name': u'GANZE',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': '0710 122 290'},
 {'address': 'Opposite the New Malindi Law and High Courts Building, Along Vasco Da Gama Road, Malindi',
  'cons_id': 5094,
  'cons_name': u'MALINDI',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': '0755556645'},
 {'address': 'OFF LAMU ROAD NEAR MUEMBE RESORT SABAKI-MALINDI TOWN',
  'cons_id': 5092,
  'cons_name': u'MAGARINI',
  'missing': False,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': '0716276617'},
 {'address': 'Milimani Estate',
  'cons_id': 5126,
  'cons_name': u'NORTH IMENTI',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0728124799'},
 {'address': 'Timau Town',
  'cons_id': 5129,
  'cons_name': u'BUURI',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0722602785'},
 {'address': 'Kianjai centre',
  'cons_id': 5127,
  'cons_name': u'TIGANIA WEST',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0721424283'},
 {'address': 'Muriri Centre',
  'cons_id': 5132,
  'cons_name': u'TIGANIA EAST',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0721702972'},
 {'address': 'D.O, Kangeta Compound',
  'cons_id': 5131,
  'cons_name': u'IGEMBE CENTRAL',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0715635177'},
 {'address': 'Laare Trading centre',
  'cons_id': 5134,
  'cons_name': u'IGEMBE NORTH',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '-'},
 {'address': 'Maua, Next to Former Municipal Council',
  'cons_id': 5130,
  'cons_name': u'IGEMBE SOUTH',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0722814240'},
 {'address': 'Gatimbi Centre',
  'cons_id': 5133,
  'cons_name': u'CENTRAL IMENTI',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0716739321'},
 {'address': 'Tetu SACCO Building, Nkubu',
  'cons_id': 5128,
  'cons_name': u'SOUTH IMENTI',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0727239281'},
 {'address': 'D.Cs Compound, Kieganguru',
  'cons_id': 5135,
  'cons_name': u'MAARA',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0721385088'},
 {'address': 'Former Municipal Compound,Chuka',
  'cons_id': 5137,
  'cons_name': u"CHUKA/IGAMBANG'OMBE",
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0721278637'},
 {'address': 'D.Cs Compound, Marimanti',
  'cons_id': 5136,
  'cons_name': u'THARAKA',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0722318211'},
 {'address': 'Near D.Cs office, along Meru-Embu highway',
  'cons_id': 5138,
  'cons_name': u'RUNYENJES',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0714130301'},
 {'address': 'Next Slopes Hotel, along Meru-Embu highway',
  'cons_id': 5140,
  'cons_name': u'MANYATTA',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0722854853'},
 {'address': 'Kiritiri Centre',
  'cons_id': 5141,
  'cons_name': u'MBEERE SOUTH',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0722697917'},
 {'address': 'D.Cs compound, Siakago',
  'cons_id': 5139,
  'cons_name': u'MBEERE NORTH',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0726896612'},
 {'address': 'Kyuso Market - Whems Building',
  'cons_id': 5346,
  'cons_name': u'MWINGI NORTH',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0710 672 857'},
 {'address': 'Migwani near Catholic Church',
  'cons_id': 5344,
  'cons_name': u'MWINGI WEST',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0702 613 173'},
 {'address': 'Mwingi Town along Kyuso \xe2\x80\x93 Tseikuru Road',
  'cons_id': 5345,
  'cons_name': u'MWINGI CENTRAL',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0712 677 688'},
 {'address': 'Matinyani Market',
  'cons_id': 5355,
  'cons_name': u'KITUI WEST',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0701 905 394'},
 {'address': 'Kwa Vonza Market - Esther House',
  'cons_id': 5354,
  'cons_name': u'KITUI RURAL',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0702 962 916'},
 {'address': 'Kitui Town (National Housing Cooperation) Opposite Kafoca Hotel',
  'cons_id': 5144,
  'cons_name': u'KITUI CENTRAL',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0718 259 376'},
 {'address': 'Nzambani District Headquarters',
  'cons_id': 5142,
  'cons_name': u'KITUI EAST',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0701 899 991'},
 {'address': 'Ikutha District Headquarters',
  'cons_id': 5143,
  'cons_name': u'KITUI SOUTH',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0718 382 907'},
 {'address': 'Masinga Market',
  'cons_id': 5149,
  'cons_name': u'MASINGA',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0711 251 018'},
 {'address': 'Kithimani \xe2\x80\x93 Yatta District Headquarters',
  'cons_id': 5145,
  'cons_name': u'YATTA',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0729 767 787'},
 {'address': 'Kangundo Town next to Probation Office',
  'cons_id': 5150,
  'cons_name': u'KANGUNDO',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0703 509 659'},
 {'address': 'Tala Town',
  'cons_id': 5147,
  'cons_name': u'MATUNGULU',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0703 509 795'},
 {'address': 'DO\xe2\x80\x99s Compound',
  'cons_id': 5152,
  'cons_name': u'KATHIANI',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0714 314 844'},
 {'address': 'Athi River Town - Martinice Villa Building Opposite Mavoko Market',
  'cons_id': 5151,
  'cons_name': u'MAVOKO',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0728 910 220'},
 {'address': 'College road Off Machakos-Nairobi road before Machakos Teachers College',
  'cons_id': 5146,
  'cons_name': u'MACHAKOS TOWN',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0772 092 057'},
 {'address': 'Makutano Ya Mwala along Machakos \xe2\x80\x93 Kitui Road',
  'cons_id': 5148,
  'cons_name': u'MWALA',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0702 664 815'},
 {'address': 'Tawa Social Hall next to Tawa Law Courts',
  'cons_id': 5242,
  'cons_name': u'MBOONI',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0701 777 833'},
 {'address': 'Salama Town along Nairobi \xe2\x80\x93 Mombasa Road',
  'cons_id': 5245,
  'cons_name': u'KILOME',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0720 159 454'},
 {'address': 'Mukuyuni Market along Machakos \xe2\x80\x93 Wote Road',
  'cons_id': 5244,
  'cons_name': u'KAITI',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0710 897 849'},
 {'address': 'Wote Town next to Makueni General Hospital',
  'cons_id': 5243,
  'cons_name': u'MAKUENI',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0705 013 016'},
 {'address': 'Makindu Town',
  'cons_id': 5241,
  'cons_name': u'KIBWEZI WEST',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0702 718 181'},
 {'address': 'Kambu Town \xe2\x80\x93 Lutheran Church Building',
  'cons_id': 5246,
  'cons_name': u'KIBWEZI EAST',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0723 632 032'},
 {'address': 'Isiolo Town, Opposite Isiolo County Government Office',
  'cons_id': 5124,
  'cons_name': u'ISIOLO NORTH',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0721450747'},
 {'address': 'Next to Kenya Red Cross Office -Garbatulla Branch',
  'cons_id': 5125,
  'cons_name': u'ISIOLO SOUTH',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0715444126'},
 {'address': 'Laisamis Town, Opposite Laisamis Primary School along Isiolo - Marsabit Highway',
  'cons_id': 5122,
  'cons_name': u'LAISAMIS',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0726403103'},
 {'address': 'Moyale Town Centre, along Marsabit- Moyale Road, Opposite Equity Bank',
  'cons_id': 5121,
  'cons_name': u'MOYALE',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0722444886'},
 {'address': 'Behind Administration Police Station',
  'cons_id': 5120,
  'cons_name': u'NORTH HORR',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0721350892'},
 {'address': 'Marsabit Town, First floor of Caltex Petrol Station Building',
  'cons_id': 5123,
  'cons_name': u'SAKU',
  'missing': False,
  'prov_id': 4,
  'prov_name': u'Eastern',
  'telephone': '0721920437'},
 {'address': 'DCs Office Compound, Kamwangi Town.',
  'cons_id': 5172,
  'cons_name': u'GATUNDU NORTH',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0722 332216'},
 {'address': 'Thika Town-DOs Office CompoundOpp Thika Stadium',
  'cons_id': 5176,
  'cons_name': u'THIKA TOWN',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0721 171820'},
 {'address': 'Limuru District Headquarters Compound',
  'cons_id': 5179,
  'cons_name': u'LIMURU',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0722 941537'},
 {'address': "Murang'a Town -County Council Building 2nd Floor",
  'cons_id': 5171,
  'cons_name': u'KIHARU',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0724 355897'},
 {'address': 'Kangema - Muguni/ Iyego Farmers Cooperative Building Opp.Kangema Police Station',
  'cons_id': 5169,
  'cons_name': u'KANGEMA',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0720 498484'},
 {'address': "Kiria-ini , Karuku's Building",
  'cons_id': 5166,
  'cons_name': u'MATHIOYA',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0719 415464'},
 {'address': 'Kangari Town, Wanyaiganji Building - Ground Floor',
  'cons_id': 5170,
  'cons_name': u'KIGUMO',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0721 435320'},
 {'address': 'World Vision Building Makuyu Opposite DOs office',
  'cons_id': 5168,
  'cons_name': u'MARAGWA',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0722 671716'},
 {'address': 'Kandara House - Kandara Town',
  'cons_id': 5167,
  'cons_name': u'KANDARA',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0729288155'},
 {'address': 'Murata Sacco Bldg.Ground Floor, Opp.Kirwara Police Station',
  'cons_id': 5177,
  'cons_name': u'GATANGA',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0202311437'},
 {'address': 'Gatundu Town Near Gatundu Law Courts',
  'cons_id': 5180,
  'cons_name': u'GATUNDU SOUTH',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0711 520005'},
 {'address': 'Juja Town -Menja Vision, Plaza',
  'cons_id': 5182,
  'cons_name': u'JUJA',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0715 509241'},
 {'address': 'Ruiru Town opposite DCs office',
  'cons_id': 5183,
  'cons_name': u'RUIRU',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0722 644454'},
 {'address': 'Githunguri- Uplands Rd -Best wing Building',
  'cons_id': 5175,
  'cons_name': u'GITHUNGURI',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0721 759745'},
 {'address': 'Kiambu Town -Biashara Street, Mapa House 4th Floor.',
  'cons_id': 5184,
  'cons_name': u'KIAMBU',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0721 363295'},
 {'address': 'Karuri \xe2\x80\x93 Banana Town',
  'cons_id': 5174,
  'cons_name': u'KIAMBAA',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0721 954135'},
 {'address': 'Kabete- Next to Rhythms College',
  'cons_id': 5173,
  'cons_name': u'KABETE',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0722 285893'},
 {'address': 'Kikuyu Town, Telcom Building - 1st Floor.',
  'cons_id': 5178,
  'cons_name': u'KIKUYU',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0722 694993'},
 {'address': 'Kagwe Township - Moi Rd - Mitundu Building',
  'cons_id': 5181,
  'cons_name': u'LARI',
  'missing': False,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': '0722 506049'},
 {'address': 'OPPOSITE AL-FURQAN INTEGRATED ACADEMY',
  'cons_id': 5111,
  'cons_name': u'WAJIR NORTH',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': ''},
 {'address': 'OPPOSITE AP CAMP.',
  'cons_id': 5115,
  'cons_name': u'WAJIR EAST',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': ''},
 {'address': 'OPPOSITE GRIFTU HOSPITAL',
  'cons_id': 5113,
  'cons_name': u'TARBAJ',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': ''},
 {'address': 'NEXT TO DC\xe2\x80\x99S RESIDENCE',
  'cons_id': 5110,
  'cons_name': u'WAJIR WEST',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': ''},
 {'address': 'NEXT TO TAKABA PRI. SCHOOL',
  'cons_id': 5114,
  'cons_name': u'ELDAS',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': ''},
 {'address': 'NEXT DC\xe2\x80\x99S OFFICE',
  'cons_id': 5112,
  'cons_name': u'WAJIR SOUTH',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': ''},
 {'address': 'OPPOSITE DC\xe2\x80\x99S',
  'cons_id': 5118,
  'cons_name': u'MANDERA WEST',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': '0722798861'},
 {'address': 'OPPOSITE POST OFFICE',
  'cons_id': 5119,
  'cons_name': u'BANISSA',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': ''},
 {'address': 'BEHIND EQUITY BANK',
  'cons_id': 5117,
  'cons_name': u'MANDERA NORTH',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': ''},
 {'address': 'NEXT TO ELWAK DC\xe2\x80\x99S OFFICE OFFICE',
  'cons_id': 5116,
  'cons_name': u'MANDERA SOUTH',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': '0722616402'},
 {'address': 'NEXT TO HABASWEIN DC\xe2\x80\x99S OFFICE',
  'cons_id': 5337,
  'cons_name': u'MANDERA EAST',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': '046-421130'},
 {'address': '',
  'cons_id': 5337,
  'cons_name': u'MANDERA EAST',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': ''},
 {'address': '',
  'cons_id': 5336,
  'cons_name': u'LAFEY',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': ''},
 {'address': 'NEXT DC OFFICE',
  'cons_id': 5108,
  'cons_name': u'FAFI',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': '0722966962'},
 {'address': 'OFF HOLA ROAD, NEXT ARILAND OFFICE',
  'cons_id': 5105,
  'cons_name': u'IJARA',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': '0722624061'},
 {'address': 'OFF UN MAIN GATE',
  'cons_id': 5106,
  'cons_name': u'DADAAB',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': '0722242632'},
 {'address': 'OPPSITE POLICE CAMP',
  'cons_id': 5109,
  'cons_name': u'LAGDERA',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': '0722348869'},
 {'address': 'BALAMBALA PRIMARY',
  'cons_id': 5104,
  'cons_name': u'BALAMBALA',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': '0711993563'},
 {'address': 'NEXT EWSO NGIRO',
  'cons_id': 5107,
  'cons_name': u'GARISSA TOWNSHIP',
  'missing': False,
  'prov_id': 6,
  'prov_name': u'North-Eastern',
  'telephone': '0720617740'},
 {'address': '',
  'cons_id': 5210,
  'cons_name': u'ALDAI',
  'missing': True,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': '',
  'cons_id': 5096,
  'cons_name': u'BURA',
  'missing': True,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5333,
  'cons_name': u'CHERANGANY',
  'missing': True,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': '',
  'cons_id': 5211,
  'cons_name': u'CHESUMEI',
  'missing': True,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': '',
  'cons_id': 5209,
  'cons_name': u'EMGWEN',
  'missing': True,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': '',
  'cons_id': 5330,
  'cons_name': u'ENDEBESS',
  'missing': True,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': '',
  'cons_id': 5095,
  'cons_name': u'GALOLE',
  'missing': True,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5097,
  'cons_name': u'GARSEN',
  'missing': True,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5162,
  'cons_name': u'GICHUGU',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5156,
  'cons_name': u'KIENI',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5334,
  'cons_name': u'KIMININI',
  'missing': True,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': '',
  'cons_id': 5154,
  'cons_name': u'KINANGOP',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5153,
  'cons_name': u'KIPIPIRI',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5163,
  'cons_name': u'KIRINYAGA CENTRAL',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5331,
  'cons_name': u'KWANZA',
  'missing': True,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': '',
  'cons_id': 5099,
  'cons_name': u'LAMU EAST',
  'missing': True,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5098,
  'cons_name': u'LAMU WEST',
  'missing': True,
  'prov_id': 3,
  'prov_name': u'Coast',
  'telephone': ''},
 {'address': '',
  'cons_id': 5157,
  'cons_name': u'MATHIRA',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5208,
  'cons_name': u'MOSOP',
  'missing': True,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': '',
  'cons_id': 5160,
  'cons_name': u'MUKURWEINI',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5165,
  'cons_name': u'MWEA',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5357,
  'cons_name': u'NANDI HILLS',
  'missing': True,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': '',
  'cons_id': 5155,
  'cons_name': u'NDARAGWA',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5164,
  'cons_name': u'NDIA',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5161,
  'cons_name': u'NYERI TOWN',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5347,
  'cons_name': u'OL JOROK',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5348,
  'cons_name': u'OL KALOU',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5158,
  'cons_name': u'OTHAYA',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5332,
  'cons_name': u'SABOTI',
  'missing': True,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''},
 {'address': '',
  'cons_id': 5159,
  'cons_name': u'TETU',
  'missing': True,
  'prov_id': 2,
  'prov_name': u'Central',
  'telephone': ''},
 {'address': '',
  'cons_id': 5356,
  'cons_name': u'TINDERET',
  'missing': True,
  'prov_id': 8,
  'prov_name': u'Rift Valley',
  'telephone': ''}]
